spring:
  datasource:
    url: jdbc:postgresql://srvpostgresqlqa.pronacej.gob.pe:5434/dbpronacejqa2
    driverClassName: org.postgresql.Driver
    username: usrqapron
    password: s2cHTh}-Tx0X!>MV
    initialization-mode: always
    initialize: true

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update

cors: http://srvfrontqa.pronacej.gob.pe,https://srvfrontqa.pronacej.gob.pe

urlFront: https://srvfrontqa.pronacej.gob.pe/pronacej-front/#

urlAlfresco: http://srvalfrescoqa.pronacej.gob.pe:8080/alfresco/api/-default-/public/alfresco/versions/1
api:
  sunat: http://165.227.80.29/apis
  reniec: http://165.227.80.29/apis