export default {
    //Regex
    REGEX_EMAIL:
        /^(([^<>()[\]\\.,;:\s@"]+(\.[^<>()[\]\\.,;:\s@"]+)*)|.(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    //Servicios no disponibles
    MENSAJE_SERVICIO_NO_DISPONIBLE:
        'Servicios no disponible, vuelve a intentarlo más tarde',
    MENSAJE_RECAPTCHAV3_ERROR:
        'Servicios de recaptcha v3 no disponibles, verifica tu conexión o intenta más tarde',

    //LocalStorage
    LS_TOKEN_DE_ACCESO: 'accessToken_pronacej',
    LS_TOKEN_EMPRESA: 'empresaIdentificador',
    LS_TOKEN_JERARQUIA: 'jerarquiaIdentificador',
    LS_TOKEN_ROL_JERARQUIA: 'rolJerarquiaIdentificador',

    PARAM_TIEMPO_INACTIVIDAD: "TIEMPO_INACTIVIDAD",

    //Nemonicos
    NEMONICO_RSA_CLAVE_PUBLICA_BACKEND: 'RSA_CLAVE_PUBLICA_BACKEND',
    NEMONICO_RSA_CLAVE_PRIVADA_FRONTEND: 'RSA_CLAVE_PRIVADA_FRONTEND',
    NEMONICO_AES_CLAVE: 'AES_CLAVE',

    //Tipo de documentos nemonico
    NEMONICO_TIPO_DOCUMENTO_SISTEMA_OTROS: 'TIPO_DOCUMENTO_SISTEMA_OTROS',
    NEMONICO_TIPO_DOCUMENTO_SISTEMA: 'TIPO_DOCUMENTO_SISTEMA',
    NEMONICO_TIPO_DE_DOCUMENTO_FICHA_PRINCIPAL_DOC_INGRESO:
        'TIPO_DE_DOCUMENTO_FICHA_PRINCIPAL_DOC_INGRESO',
    NEMONICO_TIPO_DE_DOCUMENTO_FICHA_PRINCIPAL_DOC_SALIDA:
        'TIPO_DE_DOCUMENTO_FICHA_PRINCIPAL_DOC_SALIDA',
    NEMONICO_TIPO_DOCUMENTO_SANCIONES: 'TIPO_DOCUMENTO_SISTEMA_SANCIONES',

    //Recaptcha v3
    PARAM_RECAPTCHA_V3_SITE_KEY: 'RECAPTCHA_V3_SITE_KEY',
    PARAM_RECAPTCHA_V3_ACTIVO: 'RECAPTCHA_V3_ACTIVO',
    PARAM_REGLAS_CONTRASENIA: 'REGLAS_CONTRASENIA',
    PARAM_REGLA_CONTRASENIA_MINUSCULA: 'REGLA_CONTRASENIA_MINUSCULA',
    PARAM_REGLA_CONTRASENIA_MAYUSCULA: 'REGLA_CONTRASENIA_MAYUSCULA',
    PARAM_REGLA_REGLA_CONTRASENIA_NUMERO: 'REGLA_CONTRASENIA_NUMERO',
    PARAM_REGLA_CONTRASENIA_LONGUITUD: 'REGLA_CONTRASENIA_LONGUITUD',
    PARAM_REGLA_CONTRASENIA_CARACTER_NO_ALFANUMERICO:
        'REGLA_CONTRASENIA_CARACTER_NO_ALFANUMERICO',
    PARAM_REGLA_CONTRASENIA_CAMBIO_CADA_N_DIAS:
        'REGLA_CONTRASENIA_CAMBIO_CADA_N_DIAS',

    LOGIN_CAMBIO_DE_CONTRASENIA: 'LOGIN_CAMBIO_DE_CONTRASENIA',

    //Acciones
    ACCIONES_DEL_SISTEMA: 'ACCIONES_DEL_SISTEMA',
    ACCION_LOGIN_USUARIO: 'LOGIN_USUARIO',
    ACCION_LOGIN_USUARIO_SISTEMA: 'ACCION_LOGIN_USUARIO_SISTEMA',
    ACCION_ACTUALIZAR_DATOS_USUARIO_DEL_SISTEMA:
        'ACCION_ACTUALIZAR_DATOS_USUARIO_DEL_SISTEMA',

    ACCION_CREACION_RESETEO_PASSWORD: 'ACCION_CREACION_RESETEO_PASSWORD',
    ACCION_EJECUCION_RESETEO_PASSWORD: 'ACCION_EJECUCION_RESETEO_PASSWORD',
    ACCION_EJECUCION_VERIFICACION_RESETEO_CONTRASENIA:
        'ACCION_EJECUCION_VERIFICACION_RESETEO_CONTRASENIA',

    //Valores
    NEMONICO_RSA_PUBLICA_FRONT_END: "RSA_CLAVE_PUBLICA_FRONTEND",
    /*
    RSA_PUBLICA_BACKEND:
        '-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA+M8fJQKghNWOwTOsVzIL2AVtaKdzB0Hy415i6jyhOwGWE/3f7sEUYSxV2omESH3FMQqx6xYGL9pssjQzE+ZHqxOjAG3zAfIHk/A8IziFHmvem6wGfdidDU3pf+HzRH91kmQKG1E7eaHUCvs3u9KWTLWgaPaDyq86rhGjx6Pyzr4CCKDIX0GiHj4g4SJlRp0F7ykJJUaSG+UVrN23AfTo5iJVsRcR23dhDfM9WPrGxGCgzzDAk+x0mkA+/CsW5d3Nzp6LkDobEyC74YMJ/OqRP3zi6bfS9Fiudf/KqfnFkPJ638irCpnWJ7GGe5XhreoJzhJg0lj++pmtiItcDaAzgQIDAQAB-----END PUBLIC KEY-----',
    RSA_PRIVADA_FRONTEND:
        '-----BEGIN RSA PRIVATE KEY-----MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDG3GqsFY4VBW1sjHoJnzzBEnqRtknvtBR2ireqTDH1S+yGXU0uE3P55H8CZxzY54fXxzw6PJcak8Y8jusVJSRLavihw62zz6qpv+s5wwsINl5zbIkgj9zrgQVus5MgRB0lRncUUN947TGzzvkhg3TqM+HOWc8i5NMo8rv4MXHIv4iwe/nSYOhGZ2glkmCDH/WCKw/aKgd1JK4XPQc3OfVUC0NbX7T2XU/DVs4egOwBiqDGBxaAe1/vBQQN+h6h/jGm1WH8g/npk6BMbVxh69B2/nBrMTwn4nTbJ+WJ3/XueXSDkhOWarBCBuDyWwj25OLE8ZBo+xIE0z5XtHnAcKO5AgMBAAECggEAFESPzLUvs33HnsocgBGOOCFhg6tgEsG4WjKeMImuh9EyrKkiviD2b5A1z7Fhs8u5QSlJvqfBQNCx4icw14lfDx66c4ZFlG+EdeOdHlh+LdqYusvjmAGBozEVtCgyRRYcIFnztgreE+2c5LYiFyPWTS53g7gMkAJhcSl4Nf4YGj0ZNF+WM6BqEzJ2C8NMnxcrZepSW2Tg+mQpph/aCy5W3r5TersxwseRYWOcR42vc4Nl3TpFWBFj3J/AEVNDT51mZR3vORgBwOegmOFXsgvm3KS3mRlYvnbDYVK5iRdTKuYVMP2wX55f3+uuM1PUz0Hth7x2e1X9t6yjPcgFfcRcbwKBgQDpwWAZUi7ELlAmIsLAkzMnFtEkMHzyMI0/89IpeRAT+7STN2FqJDzefTTwg+K6YjbdgymUytwWHy9rAoGiKG6/i6cPVx8j1ust7BmI7e38+lXm7KhoMcDtaRLJUvz9vkUyKDod6qpLsjCTjg6vYHIc8noDw0pZAd9kjoZhEugQCwKBgQDZyPaQQbNUuc6U/3G63ZgMXtRODp5LR0Ta1vTkQcyrPpNtM5+vLdQqyy6fLvX/wJmi2f/h7wG7XzVeIm8+kEKydIuJ0MoefmDfW0o0BS/JsV9/SZHcHO+detrq0ac6aE3bkCR+I4fXvXF2HPPoLU92mHXknRZN5w59nUlV/R+hywKBgQCGZG5KwIwwsGvWMSAFNdwv+hdOFi6P08gx342R2I+c3ZcJGMsCCkmQpS29piXBgNwIaPOMH0F/2ngZrvw27cYWjEUFNdKqeVMHOPnJVvn/+zFOLfv4w7onBMUPSI45mJ4R4zzenF9CW/U/sGnS/ME+0U3DQhFJsSDtoF+0Cfmv1wKBgDNl7WLwTo2BaJLbkpDCeX755mshohQsFsD7GELCkLYdh5evJlGmpDsRRsiEwcQBRYEcp/o/eQ4qkyLLR6vhSgxp2wDEiN8Xfm9YUTPjwXp9ZQdaapUjMx3cf8wJfMkZEr7tzt8CLa4p5Jw2iw3Rm75mjvRMapYqIM5ej48+tPdvAoGAQEbMn9niiGWugeG882U1yGm/bd164SpHiH7UbevuFLnR0UG3rtvlwHni2JkMxfRTEpq2sj/qcEw+Fm91pwrH1nC74ZTzL8HT/c+a3wAkNavoKy4lsmK9TetV/e05ZjEV8Et3amLivG5RzGU0Ix4Bt7EcQbRu31V050wVIxQI+gg=-----END RSA PRIVATE KEY-----',

        */

    //Nemonico Menus
    NEMONICO_MENU_INICIO: 'MENU_INICIO',
    NEMONICO_MENU_MENU: 'MENU_MENU',
    NEMONICO_MENU_USUARIO: 'MENU_USUARIOS',
    NEMONICO_MENU_ROL: 'MENU_ROL',
    NEMONICO_MENU_MENU_ROL: 'MENU_MENU_ROL',
    NEMONICO_MENU_AUDITORIAS_SISTEMA: 'MENU_AUDITORIAS_SISTEMA',
    NEMONICO_MENU_AUTH_LOGIN_USUARIO: 'MENU_AUTH_LOGIN_USUARIO',
    NEMONICO_MENU_PERFIL_USUARIO: 'MENU_PERFIL_USUARIO',
    NEMONICO_MENU_FUNCIONARIO: 'MENU_FUNCIONARIOS',

    NEMONICO_MENU_JERARQUIA: 'MENU_JERARQUIA',
    NEMONICO_MENU_CARGOS_JERARQUIA: 'MENU_CARGOS_JERARQUIA',
    NEMONICO_MENU_UBICACION: 'MENU_UBICACION',
    NEMONICO_MENU_UBICACIONES_JERARQUICAS: 'MENU_UBICACIONES_JERARQUICAS',
    NEMONICO_MENU_FICHA_UBICACIONES: 'MENU_FICHA_UBICACIONES',
    NEMONICO_MENU_LISTAR_FICHAS: 'MENU_FICHA_IDENTIFICACION_CREAR',
    NEMONICO_MENU_ENCUESTA: 'MENU_ENCUESTA',
    NEMONICO_MENU_NOTIFICACIONES: 'MENU_NOTIFICACIONES',
    NEMONICO_MENU_NOTIFICACIONES_DOCUMENTACION:
        'MENU_NOTIFICACIONES_DOCUMENTACION',
    NEMONICO_MENU_INFORME: 'MENU_INFORME',
    NEMONICO_MENU_INFORME_TECNICO_SUSTENTATORIO:
        'MENU_INFORME_TECNICO_SUSTENTATORIO',
    NEMONICO_MENU_INFORME_SEGUIMIENTO_PII: 'MENU_INFORME_SEGUIMIENTO_PII',
    NEMONICO_MENU_INFORME_EGRESO_PII: 'MENU_INFORME_EGRESO_PII',
    NEMONICO_MENU_INFORME_FINAL: 'MENU_INFORME_FINAL',
    NEMONICO_MENU_ACTA_EXTERNAMIENTO: 'MENU_ACTA_EXTERNAMIENTO',

    NEMONICO_MENU_REESTABLECER_CONTRASENIA: 'MENU_REESTABLECER_CONTRASENIA',
    NEMONICO_MENU_REESTABLECER_CONTRASENIA_EMPEZAR:
        'MENU_REESTABLECER_CONTRASENIA_EMPEZAR',
    NEMONICO_MENU_REESTABLECER_CONTRASENIA_REESTABLECER:
        'MENU_REESTABLECER_CONTRASENIA_REESTABLECER',
    NEMONICO_MENU_REESTABLECER_CONTRASENIA_CANCELAR:
        'MENU_REESTABLECER_CONTRASENIA_CANCELAR',

    NEMONICO_MENU_PERMISOS: 'MENU_PERMISOS_ROL_USUARIO',

    NEMONICO_REPORTE_ADOLESCENTES_EXTERNADOS: 'REPORTE_ADOLESCENTES_EXTERNADOS',

    ACCIONES_MENU_PERMISO_ROL_USUARIO: 'ACCIONES_MENU_PERMISO_ROL_USUARIO',
    ACCIONES_MENU_PERMISO_AGREGAR: 'ACCIONES_MENU_PERMISO_ROL_USUARIO_AGREGAR',
    ACCIONES_MENU_PERMISO_VER: 'ACCIONES_MENU_PERMISO_ROL_USUARIO_VER',
    ACCIONES_MENU_PERMISO_EDITAR: 'ACCIONES_MENU_PERMISO_ROL_USUARIO_EDITAR',
    ACCIONES_MENU_PERMISO_ELIMINAR: 'ACCIONES_MENU_PERMISO_ROL_USUARIO_ELIMINAR',
    

    TIPO_CENTRO: 'TIPO_CENTRO',
    TIPO_PREGUNTA: 'TIPO_PREGUNTA',
    TIPO_CAMPO: 'TIPO_CAMPO',
    TIPO_CONDUCTA: 'TIPO_CONDUCTA',
    TIPO_NOTIFICACION: 'TIPO_NOTIFICACION',
    MEDIO_NOTIFICACION: 'MEDIO_NOTIFICACION',
    PLANTILLAS_INFORME: 'PLANTILLAS_INFORME',
    CATEGORIAS_EVALUACIONES: 'CATEGORIAS_EVALUACIONES',
    TIPO_DOCUMENTO_EXTERNAMIENTO: 'TIPO_DOCUMENTO_EXTERNAMIENTO',
    AUTORIZACION_EXTERNAMIENTO: 'AUTORIZACION_EXTERNAMIENTO',
    TIPO_CENTRO_SOA: 'TIPO_CENTRO_SOA',
    TIPO_CENTRO_CJDR: 'TIPO_CENTRO_CJDR',
    TIPO_CENTRO_UAPISE: 'TIPO_CENTRO_UAPISE',
    TIPO_CENTRO_TODOS: 'TIPO_CENTRO_TODOS',

    NEMONICO_SESIONES_REFORZAMIENTO: 'SESIONES_REFORZAMIENTO',
    TIPO_DOCUMENTO_ACTA_CONSENTIMIENTO: 'TIPO_DOCUMENTO_ACTA_CONSENTIMIENTO',
    TIPO_DOCUMENTO_CARTILLA_INFORMATIVA: 'TIPO_DOCUMENTO_CARTILLA_INFORMATIVA',

    //
    NEMONICO_MENU_FICHA_IDENTIFICACION: 'MENU_FICHA_IDENTIFICACION_CREAR',
    NEMONICO_MENU_NUEVO_INGRESO: 'MENU_REGISTRO_INGRESO',

    //Nemonico Fichas de ingreso
    NEMONICO_MENU_FICHA_INGRESO: 'MENU_FICHA_INGRESO',
    NEMONICO_TIPOS_DE_DOCUMENTOS_FICHA_PRINCIPAL:
        'TIPOS_DE_DOCUMENTOS_FICHA_PRINCIPAL',

    //Nemonico Expediente Legal
    NEMONICO_MENU_EXPEDIENTE_LEGAL: 'MENU_EXPEDIENTES_LEGALES',

    //Nemonico Evaluaciones domiciliarias
    NEMONICO_MENU_EVALUACION_DOMICILIARIA: 'MENU_EVALUACION_DOMICILIARIA',

    //Nemonico Evaluaciones Sociales
    NEMONICO_MENU_EVALUACION_SOCIAL: 'MENU_EVALUACION_SOCIAL',

    //Nemonico Evaluaciones Psicologicas
    NEMONICO_MENU_EVALUACION_PSICOLOGICA: 'MENU_EVALUACION_PSICOLOGICA_FORMULARIO',

    // Agregar en etiquetas.model.ts
    NEMONICO_MENU_PRUEBAS_PSICOLOGICAS: 'MENU_PRUEBAS_PSICOLOGICAS_FORMULARIO',

    //Nemonico Evaluaciones Conductuales
    NEMONICO_MENU_EVALUACION_CONDUCTUAL: 'MENU_EVALUACION_CONDUCTUAL_FORMULARIO',

    //Nemonico Actividad Socio Recreativa
    NEMONICO_MENU_ACTIVIDAD_SOCIO_RECREATIVA: 'MENU_ACTIVIDAD_SOCIO_RECREATIVA',

    //Nemonico Evaluaciones Nivel Riesgo
    NEMONICO_MENU_NIVEL_RIESGO: 'MENU_NIVEL_RIESGO',

    //Nemonico Situaciones educativas/laborales
    NEMONICO_MENU_SITUACION_EDUCATIVA_LABORAL: 'MENU_SITUACION_EDUCATIVA_LABORAL',
    NEMONICO_MENU_SANCIONES_DISCIPLINARIAS: 'MENU_SANCION_DISCIPLINARIA',

    //Nemonico Situaciones economica/Entornos sociales
    NEMONICO_MENU_SITUACION_ECONOMICA_ENTORNO_SOCIAL:
        'MENU_SITUACION_ECONOMICA_ENTORNO_SOCIAL',

    //Nemonico Situaciones de riesgo social
    NEMONICO_MENU_SITUACION_RIESGO_SOCIAL: 'MENU_SITUACION_RIESGO_SOCIAL',
    NEMONICO_MENU_SITUACION_FAMILIAR: 'MENU_SITUACION_FAMILIAR',

    //Nemonico Orientacion/Consejería familiar
    NEMONICO_MENU_ORIENTACION_CONSEJERIA_FAMILIAR:
        'MENU_ORIENTACION_CONSEJERIA_FAMILIAR',

    //Nemonico informe de visitas
    NEMONICO_MENU_INFORME_VISITAS: 'MENU_INFORME_VISITAS',

    //Nemonico evaluación y seguimiento educativo / laboral
    NEMONICO_MENU_SEGUIMIENTO_SOCIAL: 'MENU_SEGUIMIENTO_SOCIAL',

    //Nemonico seguimiento educativo/laboral/otros
    NEMONICO_MENU_SEGUIMIENTO_EDUCATIVO_LABORAL: 'MENU_SEGUIMIENTO_EDUCATIVO_LABORAL',

    //Nemonico evaluacion educativa/laboral
    NEMONICO_MENU_EVALUACION_EDUCATIVA_LABORAL: 'MENU_EVALUACION_EDUCATIVA_LABORAL',

    //
    NEMONICO_REGISTRO_NUEVO: 'REGISTRO_NUEVO',

    //MEDICA
    NEMONICO_MENU_EVALUACION_MEDICA: 'NEMONICO_MENU_EVALUACION_MEDICA',

    NEMONICO_MENU_CONTACTO_ADOLESCENTE: 'NEMONICO_MENU_CONTACTO_ADOLESCENTE',

    NEMONICO_MENU_RELACION_ADOLESCENTES_EGRESO:
        'MENU_RELACION_ADOLESCENTES_EGRESO',

    NEMONICO_MENU_APRECIACION_FINAL: 'MENU_APRECIACION_FINAL_TRATAMIENTO',

    //REPORTES ESTADISTICOS
    NEMONICO_MENU_REPORTES_ESTADISTICOS: 'MENU_DASHBOARD_ESTADISTICAS_ADOL',

    //FICHA MEDICA
    MENU_FICHA_HISTORIA_CLINICA: 'MENU_FICHA_HISTORIA_CLINICA',
    NEMONICO_MENU_HISTORIA_CLINICA: 'MENU_HISTORIA_CLINICA',
    NEMONICO_MENU_EVALUACION_SALUD: 'MENU_EVALUACION_DE_SALUD',
    NEMONICO_MENU_FICHA_HISTORIA_CLINICA_ESQUEMA_CORPORAL_ECTOSCOPICO: 'MENU_FICHA_HISTORIA_CLINICA_ESQUEMA_CORPORAL_ECTOSCOPICO',    

    MENU_ACTIVIDADES_REFORZAMIENTO: 'MENU_ACTIVIDADES_REFORZAMIENTO',

    MENU_CATALOGOS: 'MENU_CATALOGO',
    MENU_LOCALIDADES: 'MENU_LOCALIDADES',

    NEMONICO_MENU_CONFIGURACION_TIPO_DE_ARCHIVOS_FICHA_PRINCIPAL: 'MENU_CONFIGURACION_TIPO_DE_ARCHIVOS_FICHA_PRINCIPAL',
    NEMONICO_MENU_ENCUESTAS: 'MENU_ENCUESTAS',
    NEMONICO_MENU_PLANTILLAS_INFORMES: 'MENU_PLANTILLAS_INFORMES',
    NEMONICO_MENU_PLANTILLAS: 'MENU_PLANTILLAS',
    NEMONICO_MENU_FLUJO_PROCESOS: "MENU_FLUJO_PROCESOS",
    NEMONICO_MENU_ALERTAS: "MENU_ALERTAS",


    // Plantilla base
    CONTENIDO_HTML_BASE: `<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>[TITULO-PLANTILLA]</title>
</head>
<body>`,

    CONTENIDO_HTML_BODY: `
    <p>Elabore aqu&iacute; su plantilla HTML...</p>
`,

    CONTENIDO_HTML_END: `</body>
</html>`,

    //regex
    REGEX_NUMBERS: '^[0-9]*$',

    //Secciones de la ficha de identificacion
    SECCIONES_FICHA_DE_IDENTIFICACION: 'SECCIONES_FICHA_DE_IDENTIFICACION',
    SECCION_FICHA_IDENT_FICHA_PRINCIPAL: 'SECCION_FICHA_IDENT_FICHA_PRINCIPAL',
    SECCION_FICHA_IDENT_INGRESO: 'SECCION_FICHA_IDENT_INGRESO',
    SECCION_FICHA_IDENT_EXPEDIENTE_MATRIZ:
        'SECCION_FICHA_IDENT_EXPEDIENTE_MATRIZ',
    SECCION_FICHA_IDENT_EVALUACION_MEDICA:
        'SECCION_FICHA_IDENT_EVALUACION_MEDICA',
    SECCION_FICHA_IDENT_INFORME_INICIAL: 'SECCION_FICHA_IDENT_INFORME_INICIAL',
    SECCION_FICHA_IDENT_EVALUACION_SOCIAL:
        'SECCION_FICHA_IDENT_EVALUACION_SOCIAL',
    SECCION_FICHA_IDENT_PLAN_TRATAMIENTO_INDIVIDUAL:
        'SECCION_FICHA_IDENT_PLAN_TRATAMIENTO_INDIVIDUAL',
    SECCION_FICHA_IDENT_ENTREGA_RETIRO_DE_PERTENENCIAS:
        'SECCION_FICHA_IDENT_ENTREGA_RETIRO_DE_PERTENENCIAS',
    SECCION_FICHA_IDENT_FICHA_JUDICIAL: 'SECCION_FICHA_IDENT_FICHA_JUDICIAL',
    SECCION_FICHA_IDENT_FICHA_PRINCIPAL_DOCUMENTOS_INGRESO:
        'SECCION_FICHA_IDENT_FICHA_PRINCIPAL_DOCUMENTOS_INGRESO',
    SECCION_FICHA_IDENT_FICHA_PRINCIPAL_DOCUMENTOS_SALIDA:
        'SECCION_FICHA_IDENT_FICHA_PRINCIPAL_DOCUMENTOS_SALIDA',
    SECCION_FICHA_IDENT_INFORMES: 'SECCION_FICHA_IDENT_INFORMES',
    SECCION_FICHA_IDENT_EVALUACIONES: 'SECCION_FICHA_IDENT_EVALUACIONES',
    SECCION_FICHA_IDENT_INFORME_FINAL: 'SECCION_FICHA_IDENT_INFORME_FINAL',
    SECCION_FICHA_IDENT_EXPEDIENTE_MATRIZ_ACTAS:
        'SECCION_FICHA_IDENT_EXPEDIENTE_MATRIZ_ACTAS_EXTERNAMIENTO',
    SECCION_FICHA_IDENT_PERSONA_RELACIONADA:
        'SECCION_FICHA_IDENT_PERSONA_RELACIONADA',
    SECCION_FICHA_EVALUACION_DOMICILIARIA:
        'SECCION_FICHA_IDENT_EVALUACION_DOMICILIARIA',
    SECCION_FICHA_SEGUIMIENTO_EDUCATIVO:
        'SECCION_FICHA_IDENT_SEGUIMIENTO_EDUCATIVO',
    SECCION_FICHA_IDENT_ACTIVIDADES_REFORZAMIENTO:
        'SECCION_FICHA_IDENT_ACTIVIDADES_REFORZAMIENTO',

    SECCION_FICHA_IDENT_POST_EGRESO: 'SECCION_FICHA_IDENT_POST_EGRESO',
    SECCION_FICHA_IDENT_PTI_FICHA_SEGUIMIENTO_ABIERTO:
        'SECCION_FICHA_IDENT_PTI_FICHA_SEGUIMIENTO_ABIERTO',
    SECCION_FICHA_IDENT_PTI_SEGUIMIENTO:
        'SECCION_FICHA_IDENT_PTI_SEGUIMIENTO',
    SECCION_FICHA_HISTORIA_CLINICA:
        'SECCION_FICHA_HISTORIA_CLINICA',
    SECCION_FICHA_IDENT_SANCION_DISCIPLINARIA: 'SECCION_FICHA_IDENT_SANCION_DISCIPLINARIA',

    //Historial de fotos (nemonico)
    NEMONICO_TIPO_HISTORIAL_ARCHIVOS: 'NEMONICO_TIPO_HISTORIAL_ARCHIVOS',
    NEMONICO_TIPO_HISTORIAL_ARCHIVOS_OTROS:
        'NEMONICO_TIPO_HISTORIAL_ARCHIVOS_OTROS',
    NEMONICO_TIPO_SIGNOS_ALTERACIONES_HISTORIAL:
        'NEMONICO_TIPO_SIGNOS_ALTERACIONES_HISTORIAL',

    // CLAVES PAR APERMISOS DE PANTALLAS
    ID_PANTALLA_USUARIO: 'usuario',
    ID_PANTALLA_ROL: 'rol',
    ID_PANTALLA_MENU_ROL: 'menuRol',

    //NOTIFICACIONES
    MEDIO_CORREO: 'MEDIO_CORREO',
    NOTIFICACION_OTROS: 'NOTIFICACION_OTROS',

    //ENCUESTAS
    ENCUESTA_EVALUACION_PSICOLOGICA_CJDR:
        'ENCUESTA_EVALUACIÓN_PSICOLÓGICA_CJDR',
    ENCUESTA_EVALUACION_PSICOLOGICA_SOA: 'ENCUESTA_EVALUACIÓN_PSICOLÓGICA_SOA',
    ENCUESTA_EVALUACION_PSICOLOGICA_UAPISE: 'ENCUESTA_EVALUACIÓN_PSICOLÓGICA_UAPISE',
    ENCUESTA_EVALUACION_CONDUCTUAL: 'ENCUESTA_EVALUACIÓN_CONDUCTUAL_AMBOS',
    ENCUESTA_INFORME_FINAL_CJDR: 'ENCUESTA_INFORME_FINAL_CJDR',
    ENCUESTA_INFORME_FINAL_SOA: 'ENCUESTA_INFORME_FINAL_SOA',

    //INFORMES
    PLANTILLA_ACTA_DE_CONSENTIMIENTO: 'PLANTILLA_ACTA_DE_CONSENTIMIENTO_INFORMADO_PARA_SEGUIMIENTO_POST_EGRESO',

    //CATEGORIAS DE EVALUACIONES
    CATEGORIA_GENERAL: 'CATEGORIA_GENERAL',
    CATEGORIA_PSICOLOGICA: 'CATEGORIA_PSICOLOGICA',
    CATEGORIA_PRUEBA_PSICOLOGICA: 'CATEGORIA_PRUEBA_PSICOLOGICA',
    CATEGORIA_RIESGO: 'CATEGORIA_RIESGO',

    // FORMULARIOS
    FORMULARIO_INFORME: 'FORMULARIO_INFORME',
    FORMULARIO_FICHA_IDENTIFICACION: 'FORMULARIO_FICHA_IDENTIFICACION',
    FORMULARIO_FICHA_INGRESO: 'FORMULARIO_FICHA_INGRESO',
    FORMULARIO_EVALUACION_CONDUCTUAL: 'FORMULARIO_EVALUACION_CONDUCTUAL',
    FORMULARIO_TRASLADO: 'FORMULARIO_TRASLADO',
    FORMULARIO_FUGA_ANALISTA: 'FORMULARIO_FUGA_ANALISTA',
    FORMULARIO_FUGA_DIRECTOR: 'FORMULARIO_FUGA_DIRECTOR',
    FORMULARIO_FUGA_APODERADO: 'FORMULARIO_FUGA_APODERADO',
    FORMULARIO_PERTENENCIAS_INGRESO: 'FORMULARIO_PERTENENCIAS_INGRESO',
    FORMULARIO_PERTENENCIAS_SALIDA: 'FORMULARIO_PERTENENCIAS_SALIDA',
    FORMULARIO_PTI_CERRADO: 'FORMULARIO_PTI_CERRADO',
    FORMULARIO_PTI_FICHA_SEGUIMIENTO_ABIERTO: 'FORMULARIO_PTI_FICHA_SEGUIMIENTO_ABIERTO',
    FORMULARIO_PLAN_ASISTENCIA: 'FORMULARIO_PLAN_ASISTENCIA_PE',
    FORMULARIO_PLAN_ASISTENCIA_SEGUIMIENTO: 'FORMULARIO_PLAN_ASISTENCIA_SEGUIMIENTO',
    FORMULARIO_INFORME_FINAL_ASISTENCIA: 'FORMULARIO_INFORME_FINAL_ASISTENCIA',
    FORMULARIO_PTI_ABIERTO_LIBERTAD: 'FORMULARIO_PTI_ABIERTO_LIBERTAD',
    FORMULARIO_PTI_ABIERTO_COMUNIDAD: 'FORMULARIO_PTI_ABIERTO_COMUNIDAD',
    FORMULARIO_PTI_ABIERTO_AMONESTACION: 'FORMULARIO_PTI_ABIERTO_AMONESTACION',
    FORMULARIO_PTI_ANEXO_13: 'FORMULARIO_PTI_ANEXO_13',
    FORMULARIO_PTI_ANEXO_14: 'FORMULARIO_PTI_ANEXO_14',
    FORMULARIO_PTI_ANEXO_15: 'FORMULARIO_PTI_ANEXO_15',
    FORMULARIO_ACTA_EXTERNAMIENTO: 'FORMULARIO_ACTA_EXTERNAMIENTO',
    FORMULARIO_ACTIVIDAD_REFORZAMIENTO: 'FORMULARIO_ACTIVIDAD_REFORZAMIENTO',
    FORMULARIO_ACTA_CONSENTIMIENTO: 'FORMULARIO_ACTA_CONSENTIMIENTO',
    ACTA_COMPROMISO_INSCRIPCION: 'ACTA_COMPROMISO_INSCRIPCION',
    FORMULARIO_PERMISO_SALIDA: 'FORMULARIO_PERMISO_SALIDA',
    FORMULARIO_REGISTRO_SALIDA: 'FORMULARIO_REGISTRO_SALIDA',
    FORMULARIO_INFORME_FINAL: 'FORMULARIO_INFORME_FINAL',
    FORMULARIO_INFORME_FINAL_SOA: 'FORMULARIO_INFORME_FINAL_SOA',
    FORMULARIO_GESTION_CONTACTO: 'FORMULARIO_GESTION_CONTACTO',
    FORMULARIO_ADOLESCENTE_DERIVADO: 'FORMULARIO_ADOLESCENTE_DERIVADO',
    FORMULARIO_SEGUIMIENTO_ADOLESCENTE_DERIVADO: 'FORMULARIO_SEGUIMIENTO_ADOLESCENTE_DERIVADO',
    FORMULARIO_EXPEDIENTE_LEGAL_CJDR: 'FORMULARIO_EXPEDIENTE_LEGAL_CJDR',
    FORMULARIO_EXPEDIENTE_LEGAL_SOA: 'FORMULARIO_EXPEDIENTE_LEGAL_SOA',
    FORMULARIO_SANCION_DISCIPLINARIA: 'FORMULARIO_SANCION_DISCIPLINARIA',
    FORMULARIO_HISTORIA_CLINICA_ESQUEMA_CORPORAL: 'FORMULARIO_HISTORIA_CLINICA_ESQUEMA_CORPORAL',

    //TIPOS DE INFORMACION UBICACION
    INFORMACION_PERSONAL_CORREO: 'INFORMACION_PERSONAL_CORREO',
    INFORMACION_PERSONAL_DIRECCION: 'INFORMACION_PERSONAL_DIRECCION',
    INFORMACION_PERSONAL_TELEFONO: 'INFORMACION_PERSONAL_TELEFONO',

    //CARPETAS DOCUMENTOS EVALUACIONES
    CARPETA_PSICOLOGICO: 'CARPETA_GESTION_ADOLES_PSICOLOGICO',
    CARPETA_CONDUCTUAL: 'CARPETA_GESTION_ADOLES_CONDUCTUAL',
    CARPETA_NIVEL_RIESGO: 'CARPETA_GESTION_ADOLES_NIVEL_RIESGO',
    CARPETA_INFORME_FINAL: 'CARPETA_GESTION_ADOLES_INFORME_FINAL',
    CARPETA_DOMICILIARIO: 'CARPETA_GESTION_ADOLES_EVALUACION_DOMICILIARIA',
    CARPETA_SEGUIMIENTO_EDUCATIVO: 'CARPETA_GESTION_ADOLES_SEGUIMIENTO_EDUCATIVO_LABORAL',
    CARPETA_SEGUIMIENTO_SOCIAL: 'CARPETA_GESTION_ADOLES_SEGUIMIENTO_SOCIAL',
    CARPETA_REFORZAMIENTO: 'CARPETA_GESTION_ADOLES_ACTIVIDADES_REFORZAMIENTO',
    CARPETA_FAMILIAR: 'CARPETA_GESTION_ADOLES_PERSONA_RELACIONADA',
    CARPETA_SANCIONES_DISCIPLINARIA: 'CARPETA_GESTION_ADOLES_SANCION_DISCIPLINARIA',

    //CARPETA PRINCIPAL
    NEMONICO_CARPETA_GESTION_ADOLESCENTE:
        'GESTION_ADOLESCENTECARPETA_GESTION_ADOLESCENTE',

    //MENU REGISTRO SALIDA
    NEMONICO_MENU_REGISTRO_SALIDA: 'MENU_REGISTRO_SALIDA',

    //MENU INSTITUCIONES
    NEMONICO_MENU_INSTITUCION: 'MENU_INSTITUCION',


    //NEMONICO POR ESTADOS
    NEMONICO_ESTADO_SALIDA_ACTIVO: 'ESTADO_SALIDA_ACTIVO',
    NEMONICO_ESTADO_SALIDA_CURSO: 'ESTADO_SALIDA_CURSO',
    NEMONICO_ESTADO_SALIDA_PROCESO: 'ESTADO_SALIDA_PROCESO',


    NEMONICO_MENU_PLAN_SEGUIMIENTO: 'MENU_PLAN_SEGUIMIENTO',
    NEMONICO_TIPO_DOCUMENTO_PLAN_ASISTENCIA_SEGUIMIENTO: 'TIPO_DOCUMENTO_PLAN_SEGUIMIENTO',

    //NEMONICO ESTADOS PTI
    NEMONICO_ESTADO_PTI_ACTIVO: 'ESTADO_PTI_ACTIVO',
    NEMONICO_ESTADO_PTI_BORRADOR: 'ESTADO_PTI_BORRADOR',
    NEMONICO_ESTADO_PTI_FINALIZADO: 'ESTADO_PTI_FINALIZADO',



    NEMONICO_MENU_FLUJO: 'MENU_FLUJO_INSTANCIA',

    NEMONICO_FLUJO_BANDEJA_BORRADORES: 'MENU_FLUJO_BANDEJA_BORRADORES',
    NEMONICO_FLUJO_BORRADORES_TRASLADOS: 'MENU_FLUJO_BORRADORES_TRASLADOS',
    NEMONICO_FLUJO_BORRADORES_SALIDAS: 'MENU_FLUJO_BANDEJA_SALIDA',
    NEMONICO_FLUJO_BANDEJA_ENTRADA: 'MENU_FLUJO_BANDEJA_ENTRADA',

    NEMONICO_RETIRO_PERTENENCIAS: 'MENU_RETIRO_PERTENENCIAS',
    NEMONICO_ENTREGA_RETIRO_PERTENENCIAS: 'MENU_ENTREGA_RETIRO_DE_PERTENENCIAS',
    NEMONICO_MENU_GESTION_PTI: 'MENU_GESTION_PTI',
    NEMONICO_MENU_PLAN_TRATAMIENTO_INDIVIDUAL: 'MENU_PLAN_TRATAMIENTO_INDIVIDUAL',
    NEMONICO_MENU_SEGUIMIENTO_PTI: 'MENU_SEGUIMIENTO_PTI',
    NEMONICO_MENU_PERMISO_SALIDA: 'MENU_PERMISO_DE_SALIDA',
    NEMONICO_MENU_PLAN_ASISTENCIA_POST_EGRESO: 'MENU_PLAN_ASISTENCIA_POST_EGRESO',
    NEMONICO_MENU_DERIVADO_INSTITUCIONES: 'MENU_DERIVADO_INSTITUCIONES',
    NEMONICO_MENU_SALIDAS_FINALIZADAS: 'MENU_SALIDAS_FINALIZADAS',
    NEMONICO_MENU_FICHA_FLUJOS: 'MENU_FICHA_FLUJOS',
    NEMONICO_MENU_DOCUMENTOS: 'MENU_DOCUMENTOS',
    NEMONICO_MENU_GESTION_INSTITUCION: 'MENU_GESTION_INSTITUCION',
    NEMONICO_MENU_FICHA_MEDICA: 'MENU_FICHA_MEDICA',
    NEMONICO_MENU_INFORMES: 'MENU_INFORMES',

    NEMONICO_PERMISO_TIPO_ASIGNACION: 'PERMISO_TIPO_ASIGNACION',
    NEMONICO_PERMISO_TIPO_ASIGNACION_COLABORADOR_INDIVIDUAL: 'PERMISO_TIPO_ASIGNACION_COLABORADOR_INDIVIDUAL',
    NEMONICO_PERMISO_TIPO_ASIGNACION_ROL: 'PERMISO_TIPO_ASIGNACION_ROL',
    NEMONICO_PERMISO_TIPO_PERMISO: 'PERMISO_TIPO_PERMISO',
    NEMONICO_PERMISO_TIPO_PERMISO_ESTANDAR: 'PERMISO_TIPO_PERMISO_ESTANDAR',
    NEMONICO_PERMISO_TIPO_EXCLUSION_JORNADA: 'PERMISO_TIPO_EXCLUSION_JORNADA',

    // Nemonicos estados de adolescente
    NEMONICO_ESTADO_ADOLESCENTE_LIBRE: 'ESTADO_ADOLESCENTE_LIBRE',
    NEMONICO_ESTADO_ADOLESCENTE_FUGADO: 'ESTADO_ADOLESCENTE_FUGADO',
    NEMONICO_ESTADO_ADOLESCENTE_SENTENCIADO_PROCESADO: 'ESTADO_ADOLESCENTE_SENTENCIADO_PROCESADO',
    NEMONICO_ESTADO_ADOLESCENTE_INGRESADO: 'ESTADO_ADOLESCENTE_INGRESADO',
    NEMONICO_MENU_TRABAJO_LABORAL:'MENU_TRABAJO_SOCIAL',
    NEMONICO_JERARQUIA_PADRE_UBICACION_TIPOS: 'UBICACION_TIPOS',

    NEMONICO_TIPO_ENTRADA_TRASLADO: 'ENTRADA_TRASLADO',
    NEMONICO_TIPO_ENTRADA_INGRESO_NUEVO: 'ENTRADA_INGRESO_NUEVO',
    NEMONICO_TIPO_ENTRADA_SALIDA_TEMPORAL: 'ENTRADA_SALIDA_TEMPORAL',
    NEMONICO_TIPO_ENTRADA_FUGA: 'ENTRADA_FUGA',    
};
