package net.latinus.sistema.integral.gestion.seguridad.utils;

public class EtiquetaNemonico {

    public static final String FORMAT_DATE_GSON_BUILDER = "yyyy-MM-dd'T'HH:mm:ssZ";

    //Parametros del sistema
    public static final String PARAM_JWT_CONFIGURACIONES = "JWT_CONFIGURACIONES";
    public static final String PARAM_JWT_SECRET = "JWT_SECRET";
    public static final String PARAM_JWT_SEGUNDOS_VENCIMIENTO = "JWT_SEGUNDOS_VENCIMIENTO";

    public static final String PARAM_TOKEN_SUNAT = "TOKEN_SUNAT";
    public static final String PARAM_TOKEN_RENIEC = "TOKEN_RENIEC";

    public static final String PARAM_AES_CLAVE = "AES_CLAVE";

    public static final String PARAM_RSA_CLAVE_PUBLICA_BACKEND = "RSA_CLAVE_PUBLICA_BACKEND";
    public static final String PARAM_RSA_CLAVE_PRIVADA_BACKEND = "RSA_CLAVE_PRIVADA_BACKEND";

    public static final String PARAM_RSA_CLAVE_PUBLICA_FRONTEND = "RSA_CLAVE_PUBLICA_FRONTEND";
    public static final String PARAM_RSA_CLAVE_PRIVADA_FRONTEND = "RSA_CLAVE_PRIVADA_FRONTEND";

    public static final String PARAM_RECAPTCHA_V3_CONFIGURACION = "RECAPTCHA_V3_CONFIGURACION";
    public static final String PARAM_RECAPTCHA_V3_ACTIVO = "RECAPTCHA_V3_ACTIVO";
    public static final String PARAM_RECAPTCHA_V3_SITE_KEY = "RECAPTCHA_V3_SITE_KEY";
    public static final String PARAM_RECAPTCHA_V3_SECRET_KEY = "RECAPTCHA_V3_SECRET_KEY";
    public static final String PARAM_RECAPTCHA_V3_SCORE_MIN = "RECAPTCHA_V3_SCORE_MIN";

    public static final String PARAM_HORAS_MAX_ESPERA_RESETEO_DE_CONTRASENIA = "PARAM_HORAS_MAX_ESPERA_RESETEO_DE_CONTRASENIA";

    public static final String PARAM_DIAS_DIFERENCIA_FIN_SENTENCIA = "DIAS_DIFERENCIA_FIN_SENTENCIA";

    //Menus del sistema
    public static final String MENU_REESTABLECER_CONTRASENIA_REESTABLECER = "MENU_REESTABLECER_CONTRASENIA_REESTABLECER";
    public static final String MENU_REESTABLECER_CONTRASENIA_CANCELAR = "MENU_REESTABLECER_CONTRASENIA_CANCELAR";

    //Filtros
    public static final String DIAS_MAX_ENTRE_FECHAS_FILTRO = "DIAS_MAX_ENTRE_FECHAS_FILTRO";


    //Tipos de documentos del sistema
    public static final String NEMONICO_TIPO_DOCUMENTO_SISTEMA = "TIPO_DOCUMENTO_SISTEMA";
    public static final String NEMONICO_TIPO_DOCUMENTO_SISTEMA_OTROS = "TIPO_DOCUMENTO_SISTEMA_OTROS";
    public static final String NEMONICO_TIPO_DOCUMENTO_SISTEMA_FICHA_DE_SALUD = "TIPO_DOCUMENTO_SISTEMA_FICHA_DE_SALUD";
    public static final String NEMONICO_TIPO_DOCUMENTO_CONSTANCIA_SESION_REFORZAMIENTO = "TIPO_DOCUMENTO_CONSTANCIA_SESION_REFORZAMIENTO";


    //Envio de correos
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA = "ENVIO_DE_CORREO_SISTEMA";
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA_USERNAME = "ENVIO_DE_CORREO_SISTEMA_USERNAME";
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA_AUTH = "ENVIO_DE_CORREO_SISTEMA_AUTH";
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA_TLS_ENABLE = "ENVIO_DE_CORREO_SISTEMA_TLS_ENABLE";
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA_SSL_ENABLE = "ENVIO_DE_CORREO_SISTEMA_SSL_ENABLE";
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA_HOST = "ENVIO_DE_CORREO_SISTEMA_HOST";
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA_PORT = "ENVIO_DE_CORREO_SISTEMA_PORT";
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA_DEBUG = "ENVIO_DE_CORREO_SISTEMA_DEBUG";
    public static final String PARAM_ENVIO_DE_CORREO_SISTEMA_PASSWORD = "ENVIO_DE_CORREO_SISTEMA_PASSWORD";

    //Contraseñas
    public static final String PARAM_REGLA_CONTRASENIA_CAMBIO_CADA_N_DIAS = "REGLA_CONTRASENIA_CAMBIO_CADA_N_DIAS";


    //Correos template
    public static final String CORREO_CREACION_USUARIO_SOPORTE = "CORREO_CREACION_USUARIO_SOPORTE";
    public static final String CORREO_CREACION_PROCESO_RESTABLECIMIENTO_PASSWORD = "CORREO_CREACION_PROCESO_RESTABLECIMIENTO_PASSWORD";

    //Estados Logeo
    public static final String LOGIN_EXITO = "LOGIN_EXITOSO";
    public static final String LOGIN_SELECCION_DE_EMPRESA = "LOGIN_SELECCION_DE_EMPRESA";
    public static final String LOGIN_CAMBIO_DE_CONTRASENIA = "LOGIN_CAMBIO_DE_CONTRASENIA";
    public static final String LOGIN_SELECCION_DE_JERARQUIA = "LOGIN_SELECCION_DE_JERARQUIA";


    //Valores
    public static final String SECURE_PADDING = "RSA/ECB/OAEPWITHSHA-256ANDMGF1PADDING";

    //Catalogos
    //Estados usuario
    public static final String CATA_USER_CAMBIO_DE_PASSWORD = "USER_CAMBIO_DE_PASSWORD";
    public static final String CATA_USER_CREADO = "USER_CREADO";
    public static final String CATA_USER_BLOQUEADO = "USER_BLOQUEADO";

    //Headers customs
    public static final String HEAD_TOKEN_EMPRESA = "tokenIdentificadorEmpresa";
    public static final String HEAD_NEMONICO_MENU = "nemonicoMenu";

    //Catalogo padre Informes
    public static final String PLANTILLAS_INFORME = "PLANTILLAS_INFORME";

    //Catalogo padre Encuestas
    public static final String PLANTILLAS_ENCUESTA = "PLANTILLAS_ENCUESTA";

    //Catalogo Tipo de Centro
    public static final String TIPO_CENTRO_CJDR = "TIPO_CENTRO_CJDR";
    public static final String TIPO_CENTRO_SOA = "TIPO_CENTRO_SOA";
    public static final String TIPO_CENTRO_UAPISE = "TIPO_CENTRO_UAPISE";
    public static final String TIPO_CENTRO_TODOS = "TIPO_CENTRO_TODOS";

    //Ccampo informe
    public static final String INFORME_CAMPO_BINARIO = "CAMPO_BINARIO";

    //Nemonico Peru
    public static final String PAIS_PERU = "PAIS-PERU";

    //Acciones usuario
    public static final String ACCION_AUTENTICACION_SISTEMA = "ACCION_AUTENTICACION_SISTEMA";
    public static final String ACCION_LOGIN_USUARIO_SISTEMA = "ACCION_LOGIN_USUARIO_SISTEMA";
    public static final String ACCION_CREACION_RESETEO_PASSWORD = "ACCION_CREACION_RESETEO_PASSWORD";
    public static final String ACCION_EJECUCION_RESETEO_PASSWORD = "ACCION_EJECUCION_RESETEO_PASSWORD";
    public static final String ACCION_EJECUCION_VERIFICACION_RESETEO_CONTRASENIA = "ACCION_EJECUCION_VERIFICACION_RESETEO_CONTRASENIA";

    public static final String ACCION_OBTENER_USUARIO_VALIDOS_DEL_SISTEMA = "ACCION_OBTENER_USUARIO_VALIDOS_DEL_SISTEMA";
    public static final String ACCION_ELIMINAR_USUARIO_DEL_SISTEMA = "ACCION_ELIMINAR_USUARIO_DEL_SISTEMA";
    public static final String ACCION_EDITAR_USUARIO_DEL_SISTEMA = "ACCION_EDITAR_USUARIO_DEL_SISTEMA";
    public static final String ACCION_CREAR_USUARIO_DEL_SISTEMA = "ACCION_CREAR_USUARIO_DEL_SISTEMA";
    public static final String ACCION_BLOQUEAR_USUARIO_DEL_SISTEMA = "ACCION_BLOQUEAR_USUARIO_DEL_SISTEMA";
    public static final String ACCION_ACTUALIZAR_DATOS_USUARIO_DEL_SISTEMA = "ACCION_ACTUALIZAR_DATOS_USUARIO_DEL_SISTEMA";
    public static final String ACCION_ACTUALIZAR_DATOS_DE_SEGURIDAD_DEL_USUARIO_DEL_SISTEMA = "ACCION_ACTUALIZAR_DATOS_DE_SEGURIDAD_DEL_USUARIO_DEL_SISTEMA";
    
    // Nemónicos de menús
    public static final String NEMONICO_MENU_MENU_ROL = "MENU_MENU_ROL";
    public static final String NEMONICO_MENU_ROL = "MENU_ROL";

    // Etiquetas para acciones de auditoría de roles
    public static final String ACCION_OBTENER_ROL_VALIDOS = "ACCION_OBTENER_ROL_VALIDOS";
    public static final String ACCION_CREAR_ROL = "ACCION_CREAR_ROL";
    public static final String ACCION_EDITAR_ROL = "ACCION_EDITAR_ROL";
    public static final String ACCION_ELIMINAR_ROL = "ACCION_ELIMINAR_ROL";
    public static final String ACCION_BLOQUEAR_ROL = "ACCION_BLOQUEAR_ROL";
    public static final String ACCION_BUSCAR_ROLES_POR_VALOR = "ACCION_BUSCAR_ROLES_POR_VALOR";

    // Etiquetas para acciones de auditoría del módulo Menu-Rol
    public static final String ACCION_OBTENER_MENUS_ROL = "ACCION_OBTENER_MENUS_ROL";
    public static final String ACCION_RELACIONAR_MENUS_ROL = "ACCION_RELACIONAR_MENUS_ROL";
    public static final String ACCION_BUSCAR_ROLES_MENU_ROL = "ACCION_BUSCAR_ROLES_MENU_ROL";

    //Acciones menu
    public static final String ACCION_OBTENER_MENU_VALIDOS_DEL_SISTEMA = "ACCION_OBTENER_MENU_VALIDOS_DEL_SISTEMA";
    public static final String ACCION_ELIMINAR_MENU_DEL_SISTEMA = "ACCION_ELIMINAR_MENU_DEL_SISTEMA";
    public static final String ACCION_EDITAR_MENU_DEL_SISTEMA = "ACCION_EDITAR_MENU_DEL_SISTEMA";
    public static final String ACCION_CREAR_MENU_DEL_SISTEMA = "ACCION_CREAR_MENU_DEL_SISTEMA";
    public static final String ACCION_BLOQUEAR_MENU_DEL_SISTEMA = "ACCION_BLOQUEAR_MENU_DEL_SISTEMA";
    public static final String ACCION_ACTUALIZAR_DATOS_MENU_DEL_SISTEMA = "ACCION_ACTUALIZAR_DATOS_MENU_DEL_SISTEMA";

    // Etiquetas para acciones de auditoría de funcionarios
    public static final String ACCION_CREAR_FUNCIONARIO_DEL_SISTEMA = "ACCION_CREAR_FUNCIONARIO_DEL_SISTEMA";
    public static final String ACCION_EDITAR_FUNCIONARIO_DEL_SISTEMA = "ACCION_EDITAR_FUNCIONARIO_DEL_SISTEMA";
    public static final String ACCION_ELIMINAR_FUNCIONARIO_DEL_SISTEMA = "ACCION_ELIMINAR_FUNCIONARIO_DEL_SISTEMA";
    public static final String ACCION_BLOQUEAR_FUNCIONARIO_DEL_SISTEMA = "ACCION_BLOQUEAR_FUNCIONARIO_DEL_SISTEMA";
    public static final String ACCION_OBTENER_FUNCIONARIOS_DEL_SISTEMA = "ACCION_OBTENER_FUNCIONARIOS_DEL_SISTEMA";
    public static final String ACCION_BUSCAR_FUNCIONARIOS_POR_VALOR = "ACCION_BUSCAR_FUNCIONARIOS_POR_VALOR";
    public static final String ACCION_OBTENER_FUNCIONARIO_DEL_USUARIO = "ACCION_OBTENER_FUNCIONARIO_DEL_USUARIO";

    //Acciones Jerarquía
    public static final String ACCION_OBTENER_JERARQUIA = "ACCION_OBTENER_JERARQUIA";
    public static final String ACCION_CREAR_JERARQUIA = "ACCION_CREAR_JERARQUIA";
    public static final String ACCION_EDITAR_JERARQUIA = "ACCION_EDITAR_JERARQUIA";
    public static final String ACCION_ELIMINAR_JERARQUIA = "ACCION_ELIMINAR_JERARQUIA";
    public static final String ACCION_BLOQUEAR_JERARQUIA = "ACCION_BLOQUEAR_JERARQUIA";
    public static final String ACCION_DESBLOQUEAR_JERARQUIA = "ACCION_DESBLOQUEAR_JERARQUIA";

    public static final String ACCION_CREAR_PLANTILLA_FORMULARIO = "ACCION_CREAR_PLANTILLA_FORMULARIO";
    public static final String ACCION_EDITAR_PLANTILLA_FORMULARIO = "ACCION_EDITAR_PLANTILLA_FORMULARIO";
    public static final String ACCION_ELIMINAR_PLANTILLA_FORMULARIO = "ACCION_ELIMINAR_PLANTILLA_FORMULARIO";
    public static final String ACCION_OBTENER_PLANTILLA_FORMULARIO = "ACCION_OBTENER_PLANTILLA_FORMULARIO";
    public static final String ACCION_BUSCAR_PLANTILLA_FORMULARIO = "ACCION_BUSCAR_PLANTILLA_FORMULARIO";

    public static final String ACCION_OBTENER_FICHA_IDENTIFICACION = "ACCION_OBTENER_FICHA_IDENTIFICACION";
    public static final String ACCION_OBTENER_FICHA_IDENTIFICACION_RESUMIDA = "ACCION_OBTENER_FICHA_IDENTIFICACION_RESUMIDA";
    public static final String ACCION_CREAR_FICHA_IDENTIFICACION = "ACCION_CREAR_FICHA_IDENTIFICACION";
    public static final String ACCION_EDITAR_FICHA_IDENTIFICACION = "ACCION_EDITAR_FICHA_IDENTIFICACION";
    public static final String ACCION_ELIMINAR_FICHA_IDENTIFICACION = "ACCION_ELIMINAR_FICHA_IDENTIFICACION";
    public static final String ACCION_OBTENER_FICHA_IDENTIFICACION_POR_TOKEN = "ACCION_OBTENER_FICHA_IDENTIFICACION_POR_TOKEN";
    public static final String ACCION_VALIDAR_FICHA_IDENTIFICACION = "ACCION_VALIDAR_FICHA_IDENTIFICACION";

    // Acciones de auditoría para Ficha Ingreso
    public static final String ACCION_OBTENER_FICHA_INGRESO = "ACCION_OBTENER_FICHA_INGRESO";
    public static final String ACCION_CREAR_FICHA_INGRESO = "ACCION_CREAR_FICHA_INGRESO";
    public static final String ACCION_EDITAR_FICHA_INGRESO = "ACCION_EDITAR_FICHA_INGRESO";
    public static final String ACCION_ELIMINAR_FICHA_INGRESO = "ACCION_ELIMINAR_FICHA_INGRESO";
    
    // Acciones de auditoría para Documentos de Ficha Ingreso
    public static final String ACCION_USUARIO_FICHAINGRESO_SUBIDA_DE_DOCUMENTOS = "ACCION_USUARIO_FICHAINGRESO_SUBIDA_DE_DOCUMENTOS";
    public static final String ACCION_USUARIO_FICHAINGRESO_OBTENCION_DOCUMENTOS = "ACCION_USUARIO_FICHAINGRESO_OBTENCION_DOCUMENTOS";
    public static final String ACCION_USUARIO_FICHAINGRESO_ELIMINACION_DOCUMENTOS = "ACCION_USUARIO_FICHAINGRESO_ELIMINACION_DOCUMENTOS";
    public static final String ACCION_USUARIO_FICHAINGRESO_OBTENCION_TODOS_DOCUMENTOS = "ACCION_USUARIO_FICHAINGRESO_OBTENCION_TODOS_DOCUMENTOS";

    // Acciones para Evaluación Domiciliaria
    public static final String ACCION_OBTENER_EVALUACION_DOMICILIARIA = "ACCION_OBTENER_EVALUACION_DOMICILIARIA";
    public static final String ACCION_CREAR_EVALUACION_DOMICILIARIA = "ACCION_CREAR_EVALUACION_DOMICILIARIA";
    public static final String ACCION_EDITAR_EVALUACION_DOMICILIARIA = "ACCION_EDITAR_EVALUACION_DOMICILIARIA";
    public static final String ACCION_ELIMINAR_EVALUACION_DOMICILIARIA = "ACCION_ELIMINAR_EVALUACION_DOMICILIARIA";
    public static final String ACCION_SUBIDA_DE_DOCUMENTOS_EVALUACION_DOMICILIARIA = "ACCION_SUBIDA_DE_DOCUMENTOS_EVALUACION_DOMICILIARIA";
    public static final String ACCION_SUBIR_DOCUMENTO_EVALUACION_DOMICILIARIA = "ACCION_SUBIR_DOCUMENTO_EVALUACION_DOMICILIARIA";
    public static final String ACCION_OBTENER_DOCUMENTOS_EVALUACION_DOMICILIARIA = "ACCION_OBTENER_DOCUMENTOS_EVALUACION_DOMICILIARIA";
    public static final String ACCION_ELIMINAR_DOCUMENTOS_EVALUACION_DOMICILIARIA = "ACCION_ELIMINAR_DOCUMENTOS_EVALUACION_DOMICILIARIA";

    // Acciones para Situación Económica y Entorno Social
    public static final String ACCION_OBTENER_EVALUACION_SOCIAL = "ACCION_OBTENER_EVALUACION_SOCIAL";
    public static final String ACCION_CREAR_EVALUACION_SOCIAL = "ACCION_CREAR_EVALUACION_SOCIAL";
    public static final String ACCION_EDITAR_EVALUACION_SOCIAL = "ACCION_EDITAR_EVALUACION_SOCIAL";
    public static final String ACCION_ELIMINAR_EVALUACION_SOCIAL = "ACCION_ELIMINAR_EVALUACION_SOCIAL";

    public static final String ACCION_OBTENER_EVALUACION_CONDUCTUAL = "ACCION_OBTENER_EVALUACION_CONDUCTUAL";
    public static final String ACCION_CREAR_EVALUACION_CONDUCTUAL = "ACCION_CREAR_EVALUACION_CONDUCTUAL";
    public static final String ACCION_EDITAR_EVALUACION_CONDUCTUAL = "ACCION_EDITAR_EVALUACION_CONDUCTUAL";
    public static final String ACCION_ELIMINAR_EVALUACION_CONDUCTUAL = "ACCION_ELIMINAR_EVALUACION_CONDUCTUAL";
    
    // Acciones CRUD para Actividad Ocupacional
    public static final String ACCION_OBTENER_ACTIVIDAD_OCUPACIONAL = "ACCION_OBTENER_ACTIVIDAD_OCUPACIONAL";
    public static final String ACCION_CREAR_ACTIVIDAD_OCUPACIONAL = "ACCION_CREAR_ACTIVIDAD_OCUPACIONAL";
    public static final String ACCION_EDITAR_ACTIVIDAD_OCUPACIONAL = "ACCION_EDITAR_ACTIVIDAD_OCUPACIONAL";
    public static final String ACCION_ELIMINAR_ACTIVIDAD_OCUPACIONAL = "ACCION_ELIMINAR_ACTIVIDAD_OCUPACIONAL";

    // Acciones para Seguimiento de Actividad Ocupacional
    public static final String ACCION_CREAR_SEGUIMIENTO_ACTIVIDAD_OCUPACIONAL = "ACCION_CREAR_SEGUIMIENTO_ACTIVIDAD_OCUPACIONAL";
    public static final String ACCION_OBTENER_SEGUIMIENTO_ACTIVIDAD_OCUPACIONAL = "ACCION_OBTENER_SEGUIMIENTO_ACTIVIDAD_OCUPACIONAL";
    public static final String ACCION_ELIMINAR_SEGUIMIENTO_ACTIVIDAD_OCUPACIONAL = "ACCION_ELIMINAR_SEGUIMIENTO_ACTIVIDAD_OCUPACIONAL";

    // Acciones específicas para Evaluación Psicológica
    public static final String ACCION_OBTENER_EVALUACION_PSICOLOGICA = "ACCION_OBTENER_EVALUACION_PSICOLOGICA";
    public static final String ACCION_CREAR_EVALUACION_PSICOLOGICA = "ACCION_CREAR_EVALUACION_PSICOLOGICA";
    public static final String ACCION_EDITAR_EVALUACION_PSICOLOGICA = "ACCION_EDITAR_EVALUACION_PSICOLOGICA";
    public static final String ACCION_ELIMINAR_EVALUACION_PSICOLOGICA = "ACCION_ELIMINAR_EVALUACION_PSICOLOGICA";
    public static final String ACCION_IMPRIMIR_EVALUACION_PSICOLOGICA = "ACCION_IMPRIMIR_EVALUACION_PSICOLOGICA";
    public static final String ACCION_SUBIR_DOCUMENTO_EVALUACION_PSICOLOGICA = "ACCION_SUBIR_DOCUMENTO_EVALUACION_PSICOLOGICA";
    public static final String ACCION_VER_DOCUMENTOS_EVALUACION_PSICOLOGICA = "ACCION_VER_DOCUMENTOS_EVALUACION_PSICOLOGICA";
    public static final String ACCION_REALIZAR_SEGUIMIENTO_EVALUACION_PSICOLOGICA = "ACCION_REALIZAR_SEGUIMIENTO_EVALUACION_PSICOLOGICA";

    // Acciones específicas para Pruebas Psicológicas
    public static final String ACCION_OBTENER_PRUEBAS_PSICOLOGICAS = "ACCION_OBTENER_PRUEBAS_PSICOLOGICAS";
    public static final String ACCION_CREAR_PRUEBAS_PSICOLOGICAS = "ACCION_CREAR_PRUEBAS_PSICOLOGICAS";
    public static final String ACCION_EDITAR_PRUEBAS_PSICOLOGICAS = "ACCION_EDITAR_PRUEBAS_PSICOLOGICAS";
    public static final String ACCION_ELIMINAR_PRUEBAS_PSICOLOGICAS = "ACCION_ELIMINAR_PRUEBAS_PSICOLOGICAS";
    public static final String ACCION_IMPRIMIR_PRUEBAS_PSICOLOGICAS = "ACCION_IMPRIMIR_PRUEBAS_PSICOLOGICAS";
    public static final String ACCION_SUBIR_DOCUMENTO_PRUEBAS_PSICOLOGICAS = "ACCION_SUBIR_DOCUMENTO_PRUEBAS_PSICOLOGICAS";
    public static final String ACCION_VER_DOCUMENTOS_PRUEBAS_PSICOLOGICAS = "ACCION_VER_DOCUMENTOS_PRUEBAS_PSICOLOGICAS";

    // Acciones específicas para Evaluación de Nivel de Riesgo
    public static final String ACCION_OBTENER_EVALUACION_NIVEL_RIESGO = "ACCION_OBTENER_EVALUACION_NIVEL_RIESGO";
    public static final String ACCION_CREAR_EVALUACION_NIVEL_RIESGO = "ACCION_CREAR_EVALUACION_NIVEL_RIESGO";
    public static final String ACCION_EDITAR_EVALUACION_NIVEL_RIESGO = "ACCION_EDITAR_EVALUACION_NIVEL_RIESGO";
    public static final String ACCION_ELIMINAR_EVALUACION_NIVEL_RIESGO = "ACCION_ELIMINAR_EVALUACION_NIVEL_RIESGO";
    public static final String ACCION_IMPRIMIR_EVALUACION_NIVEL_RIESGO = "ACCION_IMPRIMIR_EVALUACION_NIVEL_RIESGO";
    public static final String ACCION_SUBIR_DOCUMENTO_EVALUACION_NIVEL_RIESGO = "ACCION_SUBIR_DOCUMENTO_EVALUACION_NIVEL_RIESGO";
    public static final String ACCION_OBTENER_DOCUMENTOS_EVALUACION_NIVEL_RIESGO = "ACCION_OBTENER_DOCUMENTOS_EVALUACION_NIVEL_RIESGO";
    public static final String ACCION_DESCARGAR_EXCEL_EVALUACION_NIVEL_RIESGO = "ACCION_DESCARGAR_EXCEL_EVALUACION_NIVEL_RIESGO";

    public static final String ACCION_OBTENER_ARTEFACTO_POR_EVALUACION_SOCIAL = "ACCION_OBTENER_ARTEFACTO_POR_EVALUACION_SOCIAL";
    public static final String ACCION_CREAR_ARTEFACTO_POR_EVALUACION_SOCIAL = "ACCION_ARTEFACTO_POR_EVALUACION_SOCIAL";
    public static final String ACCION_EDITAR_ARTEFACTO_POR_EVALUACION_SOCIAL = "ACCION_ARTEFACTO_POR_EVALUACION_SOCIAL";
    public static final String ACCION_ELIMINAR_ARTEFACTO_POR_EVALUACION_SOCIAL = "ACCION_ARTEFACTO_POR_EVALUACION_SOCIAL";

    public static final String ACCION_OBTENER_SITUACION_EDUCATIVA_LABORAL = "ACCION_OBTENER_SITUACION_EDUCATIVA_LABORAL";
    public static final String ACCION_CREAR_SITUACION_EDUCATIVA_LABORAL = "ACCION_CREAR_SITUACION_EDUCATIVA_LABORAL";
    public static final String ACCION_EDITAR_SITUACION_EDUCATIVA_LABORAL = "ACCION_EDITAR_SITUACION_EDUCATIVA_LABORAL";
    public static final String ACCION_ELIMINAR_SITUACION_EDUCATIVA_LABORAL = "ACCION_ELIMINAR_SITUACION_EDUCATIVA_LABORAL";

    // Acciones para Orientación y Consejería Familiar
    public static final String ACCION_OBTENER_ORIENTACION_CONSEJERIA_FAMILIAR = "ACCION_OBTENER_ORIENTACION_CONSEJERIA_FAMILIAR";
    public static final String ACCION_CREAR_ORIENTACION_CONSEJERIA_FAMILIAR = "ACCION_CREAR_ORIENTACION_CONSEJERIA_FAMILIAR";
    public static final String ACCION_EDITAR_ORIENTACION_CONSEJERIA_FAMILIAR = "ACCION_EDITAR_ORIENTACION_CONSEJERIA_FAMILIAR";
    public static final String ACCION_ELIMINAR_ORIENTACION_CONSEJERIA_FAMILIAR = "ACCION_ELIMINAR_ORIENTACION_CONSEJERIA_FAMILIAR";

    // Nemónicos para las acciones de Informe de Visitas
    public static final String ACCION_OBTENER_INFORME_VISITAS = "ACCION_OBTENER_INFORME_VISITAS";
    public static final String ACCION_CREAR_INFORME_VISITAS = "ACCION_CREAR_INFORME_VISITAS";
    public static final String ACCION_EDITAR_INFORME_VISITAS = "ACCION_EDITAR_INFORME_VISITAS";
    public static final String ACCION_ELIMINAR_INFORME_VISITAS = "ACCION_ELIMINAR_INFORME_VISITAS";

    // Nemónicos para las acciones de Suspensión de Visitas
    public static final String ACCION_OBTENER_SUSPENSION_VISITAS = "ACCION_OBTENER_SUSPENSION_VISITAS";
    public static final String ACCION_CREAR_SUSPENSION_VISITAS = "ACCION_CREAR_SUSPENSION_VISITAS";
    public static final String ACCION_EDITAR_SUSPENSION_VISITAS = "ACCION_EDITAR_SUSPENSION_VISITAS";
    public static final String ACCION_ELIMINAR_SUSPENSION_VISITAS = "ACCION_ELIMINAR_SUSPENSION_VISITAS";

    // Nemónicos para Seguimiento Educativo/Laboral
    public static final String ACCION_OBTENER_SEGUIMIENTO_EDUCATIVO_LABORAL = "ACCION_OBTENER_SEGUIMIENTO_EDUCATIVO_LABORAL";
    public static final String ACCION_CREAR_SEGUIMIENTO_EDUCATIVO_LABORAL = "ACCION_CREAR_SEGUIMIENTO_EDUCATIVO_LABORAL";
    public static final String ACCION_EDITAR_SEGUIMIENTO_EDUCATIVO_LABORAL = "ACCION_EDITAR_SEGUIMIENTO_EDUCATIVO_LABORAL";
    public static final String ACCION_ELIMINAR_SEGUIMIENTO_EDUCATIVO_LABORAL = "ACCION_ELIMINAR_SEGUIMIENTO_EDUCATIVO_LABORAL";
    
    // Nemónicos para Evaluación Educativa Laboral
    public static final String ACCION_OBTENER_EVALUACION_EDUCATIVA_LABORAL = "ACCION_OBTENER_EVALUACION_EDUCATIVA_LABORAL";
    public static final String ACCION_CREAR_EVALUACION_EDUCATIVA_LABORAL = "ACCION_CREAR_EVALUACION_EDUCATIVA_LABORAL";
    public static final String ACCION_EDITAR_EVALUACION_EDUCATIVA_LABORAL = "ACCION_EDITAR_EVALUACION_EDUCATIVA_LABORAL";
    public static final String ACCION_ELIMINAR_EVALUACION_EDUCATIVA_LABORAL = "ACCION_ELIMINAR_EVALUACION_EDUCATIVA_LABORAL";

    // Acciones para Situación de Riesgo Social
    public static final String ACCION_OBTENER_SITUACION_RIESGO_SOCIAL = "ACCION_OBTENER_SITUACION_RIESGO_SOCIAL";
    public static final String ACCION_CREAR_SITUACION_RIESGO_SOCIAL = "ACCION_CREAR_SITUACION_RIESGO_SOCIAL";
    public static final String ACCION_EDITAR_SITUACION_RIESGO_SOCIAL = "ACCION_EDITAR_SITUACION_RIESGO_SOCIAL";
    public static final String ACCION_ELIMINAR_SITUACION_RIESGO_SOCIAL = "ACCION_ELIMINAR_SITUACION_RIESGO_SOCIAL";

    public static final String ACCION_ELIMINAR_EXPEDIENTE = "ACCION_ELIMINAR_EXPEDIENTE";
    public static final String ACCION_EDITAR_EXPEDIENTE = "ACCION_EDITAR_EXPEDIENTE";
    public static final String ACCION_CREAR_EXPEDIENTE = "ACCION_CREAR_EXPEDIENTE";
    public static final String ACCION_LISTAR_EXPEDIENTE = "ACCION_LISTAR_EXPEDIENTE";

    public static final String ACCION_ELIMINAR_PERTENENCIA = "ACCION_ELIMINAR_PERTENENCIA";
    public static final String ACCION_EDITAR_PERTENENCIA = "ACCION_EDITAR_PERTENENCIA";
    public static final String ACCION_CREAR_PERTENENCIA = "ACCION_CREAR_PERTENENCIA";
    public static final String ACCION_LISTAR_PERTENENCIA = "ACCION_LISTAR_PERTENENCIA";

    public static final String ACCION_ELIMINAR_PLAN_ASISTENCIA = "ACCION_ELIMINAR_PLAN_ASISTENCIA";
    public static final String ACCION_EDITAR_PLAN_ASISTENCIA = "ACCION_EDITAR_PLAN_ASISTENCIA";
    public static final String ACCION_CREAR_PLAN_ASISTENCIA = "ACCION_CREAR_PLAN_ASISTENCIA";

    public static final String ACCION_ELIMINAR_PLAN = "ACCION_ELIMINAR_PLAN";
    public static final String ACCION_EDITAR_PLAN = "ACCION_EDITAR_PLAN";
    public static final String ACCION_CREAR_PLAN = "ACCION_CREAR_PLAN";
    public static final String ACCION_LISTAR_PLAN = "ACCION_LISTAR_PLAN";

    public static final String ACCION_ELIMINAR_INFORME_FINAL_ABIERTO = "ACCION_ELIMINAR_INFORME_FINAL_ABIERTO";
    public static final String ACCION_EDITAR_INFORME_FINAL_ABIERTO = "ACCION_EDITAR_INFORME_FINAL_ABIERTO";
    public static final String ACCION_CREAR_INFORME_FINAL_ABIERTO = "ACCION_CREAR_INFORME_FINAL_ABIERTO";

    public static final String ACCION_ELIMINAR_PLAN_SEGUIMIENTO = "ACCION_ELIMINAR_PLAN_SEGUIMIENTO";
    public static final String ACCION_EDITAR_PLAN_SEGUIMIENTO = "ACCION_EDITAR_PLAN_SEGUIMIENTO";
    public static final String ACCION_CREAR_PLAN_SEGUIMIENTO = "ACCION_CREAR_PLAN_SEGUIMIENTO";

    public static final String ACCION_ELIMINAR_INFORME_FINAL_ASISTENCIA = "ACCION_ELIMINAR_INFORME_FINAL_ASISTENCIA";
    public static final String ACCION_EDITAR_INFORME_FINAL_ASISTENCIA = "ACCION_EDITAR_INFORME_FINAL_ASISTENCIA";
    public static final String ACCION_CREAR_INFORME_FINAL_ASISTENCIA = "ACCION_CREAR_INFORME_FINAL_ASISTENCIA";

    public static final String ACCION_OBTENER_PROCESO = "ACCION_OBTENER_PROCESO";
    public static final String ACCION_CREAR_PROCESO = "ACCION_CREAR_PROCESO";
    public static final String ACCION_EDITAR_PROCESO = "ACCION_EDITAR_PROCESO";
    public static final String ACCION_ELIMINAR_PROCESO = "ACCION_ELIMINAR_PROCESO";
    
    public static final String ACCION_OBTENER_TAREA = "ACCION_OBTENER_TAREA";
    public static final String ACCION_CREAR_TAREA = "ACCION_CREAR_TAREA";
    public static final String ACCION_EDITAR_TAREA = "ACCION_EDITAR_TAREA";
    public static final String ACCION_ELIMINAR_TAREA = "ACCION_ELIMINAR_TAREA";

    public static final String ACCION_ELIMINAR_INSTANCIA_PROCESO = "ACCION_ELIMINAR_INSTANCIA_PROCESO";
    public static final String ACCION_EDITAR_INSTANCIA_PROCESO = "ACCION_EDITAR_INSTANCIA_PROCESO";
    public static final String ACCION_CREAR_INSTANCIA_PROCESO = "ACCION_CREAR_INSTANCIA_PROCESO";
    public static final String ACCION_LISTAR_INSTANCIA_PROCESO = "ACCION_LISTAR_INSTANCIA_PROCESO";

    public static final String ACCION_ELIMINAR_TRASLADO = "ACCION_ELIMINAR_TRASLADO";
    public static final String ACCION_EDITAR_TRASLADO = "ACCION_EDITAR_TRASLADO";
    public static final String ACCION_CREAR_TRASLADO = "ACCION_CREAR_TRASLADO";
    public static final String ACCION_OBTENER_TRASLADO = "ACCION_OBTENER_TRASLADO";

    // Nemónicos para módulo de Apreciación Final del Tratamiento
    public static final String NEMONICO_MENU_APRECIACION_FINAL = "NEMONICO_MENU_APRECIACION_FINAL";
    public static final String ACCION_OBTENER_APRECIACION_FINAL = "ACCION_OBTENER_APRECIACION_FINAL";
    public static final String ACCION_CREAR_APRECIACION_FINAL = "ACCION_CREAR_APRECIACION_FINAL";
    public static final String ACCION_EDITAR_APRECIACION_FINAL = "ACCION_EDITAR_APRECIACION_FINAL";
    public static final String ACCION_ELIMINAR_APRECIACION_FINAL = "ACCION_ELIMINAR_APRECIACION_FINAL";
    public static final String ACCION_ELIMINAR_SITUACION_ADOLESCENTE = "ACCION_ELIMINAR_SITUACION_ADOLESCENTE";
    public static final String ACCION_ELIMINAR_FACTOR_PRESENTE = "ACCION_ELIMINAR_FACTOR_PRESENTE";

    // Grupo principal de acciones para persona relacionada (datos familiares)

    // Acciones para datos familiares en general
    public static final String ACCION_CREAR_DATOS_FAMILIARES = "ACCION_CREAR_DATOS_FAMILIARES";
    public static final String ACCION_OBTENER_DATOS_FAMILIARES = "ACCION_OBTENER_DATOS_FAMILIARES";
    public static final String ACCION_EDITAR_DATOS_FAMILIARES = "ACCION_EDITAR_DATOS_FAMILIARES";
    public static final String ACCION_ELIMINAR_DATOS_FAMILIARES = "ACCION_ELIMINAR_DATOS_FAMILIARES";

    // Acciones para gestión de documentos de datos familiares
    public static final String ACCION_USUARIO_DATOS_FAMILIARES_SUBIDA_DE_DOCUMENTOS = "ACCION_USUARIO_DATOS_FAMILIARES_SUBIDA_DE_DOCUMENTOS";
    public static final String ACCION_USUARIO_DATOS_FAMILIARES_OBTENCION_DOCUMENTOS = "ACCION_USUARIO_DATOS_FAMILIARES_OBTENCION_DOCUMENTOS";
    public static final String ACCION_USUARIO_DATOS_FAMILIARES_ELIMINACION_DOCUMENTOS = "ACCION_USUARIO_DATOS_FAMILIARES_ELIMINACION_DOCUMENTOS";

    // Acciones específicas para persona relacionada
    public static final String ACCION_OBTENER_PERSONAS_RELACIONADAS = "ACCION_OBTENER_PERSONAS_RELACIONADAS";
    public static final String ACCION_OBTENER_PERSONA_RELACIONADA = "ACCION_OBTENER_PERSONA_RELACIONADA";
    public static final String ACCION_CREAR_PERSONA_RELACIONADA = "ACCION_CREAR_PERSONA_RELACIONADA";
    public static final String ACCION_EDITAR_PERSONA_RELACIONADA = "ACCION_EDITAR_PERSONA_RELACIONADA";
    public static final String ACCION_ELIMINAR_PERSONA_RELACIONADA = "ACCION_ELIMINAR_PERSONA_RELACIONADA";

    // Acciones para direcciones de persona relacionada
    public static final String ACCION_CREAR_DIRECCION_PERSONA_RELACIONADA = "ACCION_CREAR_DIRECCION_PERSONA_RELACIONADA";
    public static final String ACCION_ELIMINAR_DIRECCION_PERSONA_RELACIONADA = "ACCION_ELIMINAR_DIRECCION_PERSONA_RELACIONADA";

    // Acciones para información de ubicación
    public static final String ACCION_OBTENER_INFORMACION_UBICACIONES = "ACCION_OBTENER_INFORMACION_UBICACIONES";
    public static final String ACCION_CREAR_INFORMACION_UBICACION = "ACCION_CREAR_INFORMACION_UBICACION";
    public static final String ACCION_ELIMINAR_INFORMACION_UBICACION = "ACCION_ELIMINAR_INFORMACION_UBICACION";

    //Acciones Localidad
    public static final String ACCION_OBTENER_UBIGEO = "ACCION_OBTENER_UBIGEO";

    //Acciones usuario documento
    public static final String ACCION_DOCUMENTO = "ACCION_DOCUMENTO";
    public static final String ACCION_DOCUMENTO_SUBIDA = "ACCION_DOCUMENTO_SUBIDA";
    public static final String ACCION_DOCUMENTO_ELIMINAR = "ACCION_DOCUMENTO_ELIMINAR";
    public static final String ACCION_DOCUMENTO_OBTENER = "ACCION_DOCUMENTO_OBTENER";

    // Acciones para Encuestas
    public static final String ACCION_OBTENER_LISTA_ENCUESTA = "ACCION_OBTENER_LISTA_ENCUESTA";
    public static final String ACCION_OBTENER_ENCUESTA = "ACCION_OBTENER_ENCUESTA";
    public static final String ACCION_CREAR_ENCUESTA = "ACCION_CREAR_ENCUESTA";
    public static final String ACCION_EDITAR_ENCUESTA = "ACCION_EDITAR_ENCUESTA";
    public static final String ACCION_ELIMINAR_ENCUESTA = "ACCION_ELIMINAR_ENCUESTA";

    // Acciones para Evaluaciones
    public static final String ACCION_OBTENER_EVALUACION = "ACCION_OBTENER_EVALUACION";
    public static final String ACCION_CREAR_EVALUACION = "ACCION_CREAR_EVALUACION";
    public static final String ACCION_EDITAR_EVALUACION = "ACCION_EDITAR_EVALUACION";
    public static final String ACCION_ELIMINAR_EVALUACION = "ACCION_ELIMINAR_EVALUACION";

    // Acciones para Historia Clínica
    public static final String ACCION_USUARIO_FICHA_MEDICA_SUBIDA_DE_DOCUMENTOS = "ACCION_USUARIO_FICHA_MEDICA_SUBIDA_DE_DOCUMENTOS";
    public static final String ACCION_USUARIO_FICHA_MEDICA_OBTENCION_DOCUMENTOS = "ACCION_USUARIO_FICHA_MEDICA_OBTENCION_DOCUMENTOS";
    public static final String ACCION_USUARIO_FICHA_MEDICA_ELIMINACION_DOCUMENTOS = "ACCION_USUARIO_FICHA_MEDICA_ELIMINACION_DOCUMENTOS";

    // Acciones para Documentos de Evaluación
    public static final String ACCION_SUBIR_EVALUACION_DOCUMENTO = "ACCION_SUBIR_EVALUACION_DOCUMENTO";
    public static final String ACCION_OBTENER_DOCUMENTOS_EVALUACION = "ACCION_OBTENER_DOCUMENTOS_EVALUACION";

    //Acciones Informe
    public static final String ACCION_OBTENER_LISTA_INFORME = "ACCION_OBTENER_LISTA_INFORME";
    public static final String ACCION_OBTENER_INFORME = "ACCION_OBTENER_INFORME";
    public static final String ACCION_CREAR_INFORME = "ACCION_CREAR_INFORME";
    public static final String ACCION_EDITAR_INFORME = "ACCION_EDITAR_INFORME";
    public static final String ACCION_ELIMINAR_INFORME = "ACCION_ELIMINAR_INFORME";
    public static final String ACCION_SUBIR_INFORME = "ACCION_SUBIR_INFORME";

    public static final String ACCION_OBTENER_LISTA_PLANTILLA_INFORME = "ACCION_OBTENER_LISTA_PLANTILLA_INFORME";
    public static final String ACCION_OBTENER_PLANTILLA_INFORME = "ACCION_OBTENER_PLANTILLA_INFORME";
    public static final String ACCION_CREAR_PLANTILLA_INFORME = "ACCION_CREAR_PLANTILLA_INFORME";
    public static final String ACCION_EDITAR_PLANTILLA_INFORME = "ACCION_EDITAR_PLANTILLA_INFORME";
    public static final String ACCION_ELIMINAR_PLANTILLA_INFORME = "ACCION_ELIMINAR_PLANTILLA_INFORME";

    // Nemónicos para Informe Técnico Sustentatorio
    public static final String ACCION_OBTENER_INFORME_TECNICO = "ACCION_OBTENER_INFORME_TECNICO";
    public static final String ACCION_CREAR_INFORME_TECNICO = "ACCION_CREAR_INFORME_TECNICO";
    public static final String ACCION_EDITAR_INFORME_TECNICO = "ACCION_EDITAR_INFORME_TECNICO";
    public static final String ACCION_ELIMINAR_INFORME_TECNICO = "ACCION_ELIMINAR_INFORME_TECNICO";

    // Nemónicos para Informe de Seguimiento PII
    public static final String ACCION_OBTENER_INFORME_SEGUIMIENTO = "ACCION_OBTENER_INFORME_SEGUIMIENTO";
    public static final String ACCION_CREAR_INFORME_SEGUIMIENTO = "ACCION_CREAR_INFORME_SEGUIMIENTO";
    public static final String ACCION_EDITAR_INFORME_SEGUIMIENTO = "ACCION_EDITAR_INFORME_SEGUIMIENTO";
    public static final String ACCION_ELIMINAR_INFORME_SEGUIMIENTO = "ACCION_ELIMINAR_INFORME_SEGUIMIENTO";

    // Nemónicos para Informe de Egreso PII
    public static final String ACCION_OBTENER_INFORME_EGRESO_PII = "ACCION_OBTENER_INFORME_EGRESO_PII";
    public static final String ACCION_CREAR_INFORME_EGRESO_PII = "ACCION_CREAR_INFORME_EGRESO_PII";
    public static final String ACCION_EDITAR_INFORME_EGRESO_PII = "ACCION_EDITAR_INFORME_EGRESO_PII";
    public static final String ACCION_ELIMINAR_INFORME_EGRESO_PII = "ACCION_ELIMINAR_INFORME_EGRESO_PII";

    //Estados reseteo de contraseñas
    public static final String RESETEO_DE_CONTRASENIA = "RESETEO_DE_CONTRASENIA";
    public static final String NEMONICO_RESETEO_DE_PASSWORD_PENDIENTE = "RESETEO_DE_CONTRASENIA_PENDIENTE";
    public static final String NEMONICO_RESETEO_DE_PASSWORD_COMPLETADO = "RESETEO_DE_CONTRASENIA_COMPLETADO";
    public static final String NEMONICO_RESETEO_DE_PASSWORD_CANCELADO = "RESETEO_DE_CONTRASENIA_CANCELADO";
    public static final String NEMONICO_RESETEO_DE_CONTRASENIA_CADUCADO = "RESETEO_DE_CONTRASENIA_CADUCADO";
    
    // Acciones en la ficha principal - Documentos
    public static final String ACCION_USUARIO_FICHA_PRINCIPAL = "ACCION_USUARIO_FICHA_PRINCIPAL";
    public static final String ACCION_USUARIO_FICHA_PRINCIPAL_SUBIDA_DE_DOCUMENTOS = "ACCION_USUARIO_FICHA_PRINCIPAL_SUBIDA_DE_DOCUMENTOS";
    public static final String ACCION_USUARIO_FICHA_PRINCIPAL_OBTENCION_DOCUMENTOS = "ACCION_USUARIO_FICHA_PRINCIPAL_OBTENCION_DOCUMENTOS";
    public static final String ACCION_USUARIO_FICHA_PRINCIPAL_ELIMINACION_DOCUMENTOS = "ACCION_USUARIO_FICHA_PRINCIPAL_ELIMINACION_DOCUMENTOS";

    // Acciones para Ficha Identificación Tipo de Documento
    public static final String ACCION_OBTENER_FICHA_IDENTIFICACION_TIPO_DOCUMENTO = "ACCION_OBTENER_FICHA_IDENTIFICACION_TIPO_DOCUMENTO";
    public static final String ACCION_CREAR_FICHA_IDENTIFICACION_TIPO_DOCUMENTO = "ACCION_CREAR_FICHA_IDENTIFICACION_TIPO_DOCUMENTO";
    public static final String ACCION_EDITAR_FICHA_IDENTIFICACION_TIPO_DOCUMENTO = "ACCION_EDITAR_FICHA_IDENTIFICACION_TIPO_DOCUMENTO";
    public static final String ACCION_ELIMINAR_FICHA_IDENTIFICACION_TIPO_DOCUMENTO = "ACCION_ELIMINAR_FICHA_IDENTIFICACION_TIPO_DOCUMENTO";
    public static final String ACCION_OBTENER_RESUMEN_FICHA_IDENTIFICACION_TIPO_DOCUMENTO = "ACCION_OBTENER_RESUMEN_FICHA_IDENTIFICACION_TIPO_DOCUMENTO";
    public static final String ACCION_OBTENER_TIPOS_DOCUMENTOS_POR_SECCION = "ACCION_OBTENER_TIPOS_DOCUMENTOS_POR_SECCION";

    public static final String ACCION_USUARIO_SECCION_FICHA_PRINCIPAL_TIPO_DE_DOCUMENTO_CREACION = "ACCION_USUARIO_SECCION_FICHA_PRINCIPAL_TIPO_DE_DOCUMENTO_CREACION";
    public static final String ACCION_USUARIO_SECCION_FICHA_PRINCIPAL_TIPO_DE_DOCUMENTO_EDICION = "ACCION_USUARIO_SECCION_FICHA_PRINCIPAL_TIPO_DE_DOCUMENTO_EDICION";
    public static final String ACCION_USUARIO_SECCION_FICHA_PRINCIPAL_TIPO_DE_DOCUMENTO_ELIMINACION = "ACCION_USUARIO_SECCION_FICHA_PRINCIPAL_TIPO_DE_DOCUMENTO_ELIMINACION";


    public static final String ACCION_USUARIO_FICHA_PRINCIPAL_OBTENER_DATO_CARPETA = "ACCION_USUARIO_FICHA_PRINCIPAL_OBTENER_DATO_CARPETA";


    //Notificaciones
    public static final String ACCION_OBTENER_NOTIFICACIONES = "ACCION_OBTENER_NOTIFICACIONES";
    public static final String ACCION_ENVIO_DE_EMAIL = "ACCION_ENVIO_DE_EMAIL";
    public static final String ACCION_ENVIO_DE_EMAIL_NOTIFICACION = "ACCION_ENVIO_DE_EMAIL_NOTIFICACION";

    //Reportes
    public static final String ACCION_OBTENER_REPORTE_DELITOS = "ACCION_OBTENER_REPORTE_DELITOS";
    public static final String ACCION_OBTENER_REPORTE_POBLACION_CENTROS = "ACCION_OBTENER_REPORTE_POBLACION_CENTROS";
    public static final String ACCION_OBTENER_REPORTE_POBLACION_EDAD = "ACCION_OBTENER_REPORTE_POBLACION_EDAD";
    public static final String ACCION_OBTENER_REPORTE_POBLACION_ESTADOS = "ACCION_OBTENER_REPORTE_POBLACION_ESTADOS";
    public static final String ACCION_OBTENER_DETALLE_EXPEDIENTE = "ACCION_OBTENER_DETALLE_EXPEDIENTE";


    //Gestion del adolescente carpetas que se crean al momento de crear una nueva ficha de identificacion
    public static final String CARPETA_GESTION_ADOLESCENTE = "GESTION_ADOLESCENTECARPETA_GESTION_ADOLESCENTE";
    public static final String CARPETA_GESTION_ADOLES_DOC_PERSONALES = "CARPETA_GESTION_ADOLES_DOC_PERSONALES";
    public static final String CARPETA_GESTION_ADOLES_LEGAL = "CARPETA_GESTION_ADOLES_LEGAL";
    public static final String CARPETA_GESTION_ADOLES_PSICOLOGICO = "CARPETA_GESTION_ADOLES_PSICOLOGICO";
    public static final String CARPETA_GESTION_ADOLES_SALUD = "CARPETA_GESTION_ADOLES_SALUD";
    public static final String CARPETA_GESTION_ADOLES_TRABAJO_SOCIAL = "CARPETA_GESTION_ADOLES_TRABAJO_SOCIAL";
    public static final String CARPETA_GESTION_ADOLES_CONDUCTUAL = "CARPETA_GESTION_ADOLES_CONDUCTUAL";
    public static final String CARPETA_GESTION_ADOLES_PTI = "CARPETA_GESTION_ADOLES_PTI";
    public static final String CARPETA_GESTION_ADOLES_INCIDENCIAS = "CARPETA_GESTION_ADOLES_INCIDENCIAS";
    public static final String CARPETA_GESTION_ADOLES_INFORMES = "CARPETA_GESTION_ADOLES_INFORMES";
    public static final String CARPETA_GESTION_ADOLES_NOTIFICACIONES = "CARPETA_GESTION_ADOLES_NOTIFICACIONES";
    public static final String CARPETA_GESTION_ADOLES_IMAGENES = "CARPETA_GESTION_ADOLES_IMAGENES";
    public static final String CARPETA_GESTION_ADOLES_PERTENENCIAS = "CARPETA_GESTION_ADOLES_PERTENENCIAS";
    public static final String CARPETA_GESTION_HISTORIA_CLINICA = "CARPETA_GESTION_HISTORIA_CLINICA";
    public static final String CARPETA_GESTION_ADOLES_POST_EGRESO = "CARPETA_GESTION_ADOLES_POST_EGRESO";
    public static final String CARPETA_GESTION_ADOLES_POST_EGRESO_PLAN_ASISTENCIA = "CARPETA_GESTION_ADOLES_POST_EGRESO_PLAN_ASISTENCIA";
    public static final String CARPETA_GESTION_ADOLES_POST_EGRESO_PLAN_ASISTENCIA_SEGUIMIENTO = "CARPETA_GESTION_ADOLES_POST_EGRESO_PLAN_ASISTENCIA_SEGUIMIENTO";
    public static final String CARPETA_GESTION_ADOLES_INTERVENCION_DIF = "CARPETA_GESTION_ADOLES_INTERVENCION_DIF";
    public static final String CARPETA_GESTION_ADOLES_FICHA_INGRESO = "CARPETA_GESTION_ADOLES_FICHA_INGRESO";
    public static final String CARPETA_GESTION_EVALUACION_MEDICA_PROGRESO = "CARPETA_GESTION_EVALUACION_MEDICA_PROGRESO";
    public static final String CARPETA_NIVEL_RIESGO = "CARPETA_GESTION_ADOLES_NIVEL_RIESGO";
    public static final String CARPETA_GESTION_ADOLES_EVALUACION_DOMICILIARIA = "CARPETA_GESTION_ADOLES_EVALUACION_DOMICILIARIA";
    public static final String CARPETA_GESTION_ADOLES_SEGUIMIENTO_EDUCATIVO_LABORAL = "CARPETA_GESTION_ADOLES_SEGUIMIENTO_EDUCATIVO_LABORAL";
    public static final String CARPETA_GESTION_ADOLES_SEGUIMIENTO_SOCIAL = "CARPETA_GESTION_ADOLES_SEGUIMIENTO_SOCIAL";
    public static final String CARPETA_GESTION_ADOLES_ACTIVIDADES_REFORZAMIENTO = "CARPETA_GESTION_ADOLES_ACTIVIDADES_REFORZAMIENTO";
    public static final String CARPETA_GESTION_ADOLES_FICHA_PSICOSOCIAL = "CARPETA_GESTION_ADOLES_FICHA_PSICOSOCIAL";
    public static final String CARPETA_GESTION_ADOLES_INFORME_FINAL = "CARPETA_GESTION_ADOLES_INFORME_FINAL";
    public static final String CARPETA_GESTION_ADOLES_SANCION_DISCIPLINARIA = "CARPETA_GESTION_ADOLES_SANCION_DISCIPLINARIA";
    public static final String CARPETA_GESTION_ADOLES_SEGUIMIENTO_EDUCATIVO_LABORAL_OTROS = "CARPETA_GESTION_ADOLES_SEGUIMIENTO_EDUCATIVO_LABORAL_OTROS";


    //Secciones de ficha de identificacion
    public static final String SECCIONES_FICHA_DE_IDENTIFICACION = "SECCIONES_FICHA_DE_IDENTIFICACION";
    public static final String SECCION_FICHA_IDENT_FICHA_PRINCIPAL = "SECCION_FICHA_IDENT_FICHA_PRINCIPAL";
    public static final String SECCION_FICHA_IDENT_INGRESO = "SECCION_FICHA_IDENT_INGRESO";
    public static final String SECCION_FICHA_IDENT_EXPEDIENTE_MATRIZ = "SECCION_FICHA_IDENT_EXPEDIENTE_MATRIZ";
    public static final String SECCION_FICHA_IDENT_EVALUACION_MEDICA = "SECCION_FICHA_IDENT_EVALUACION_MEDICA";
    public static final String SECCION_FICHA_IDENT_INFORME_INICIAL = "SECCION_FICHA_IDENT_INFORME_INICIAL";
    public static final String SECCION_FICHA_IDENT_EVALUACION_SOCIAL = "SECCION_FICHA_IDENT_EVALUACION_SOCIAL";
    public static final String SECCION_FICHA_IDENT_PLAN_TRATAMIENTO_INDIVIDUAL = "SECCION_FICHA_IDENT_PLAN_TRATAMIENTO_INDIVIDUAL";
    public static final String SECCION_FICHA_IDENT_ENTREGA_RETIRO_DE_PERTENENCIAS = "SECCION_FICHA_IDENT_ENTREGA_RETIRO_DE_PERTENENCIAS";
    public static final String SECCION_FICHA_IDENT_FICHA_JUDICIAL = "SECCION_FICHA_IDENT_FICHA_JUDICIAL";

    // Nuevas secciones para exportar en CSV
    public static final String SECCION_FICHA_IDENT_EXPEDIENTE_MATRIZ_ACTAS_EXTERNAMIENTO = "SECCION_FICHA_IDENT_EXPEDIENTE_MATRIZ_ACTAS_EXTERNAMIENTO";
    public static final String SECCION_FICHA_IDENT_FICHA_PSICOSOCIAL = "SECCION_FICHA_IDENT_FICHA_PSICOSOCIAL";
    public static final String SECCION_FICHA_IDENT_FICHA_PSICOSOCIAL_SITUACION_ECONOMICA = "SECCION_FICHA_IDENT_FICHA_PSICOSOCIAL_SITUACION_ECONOMICA";
    public static final String SECCION_FICHA_IDENT_FICHA_PSICOSOCIAL_SITUACION_EDUCATIVA = "SECCION_FICHA_IDENT_FICHA_PSICOSOCIAL_SITUACION_EDUCATIVA";
    public static final String SECCION_FICHA_IDENT_FICHA_PSICOSOCIAL_SITUACION_RIESGO_SOCIAL = "SECCION_FICHA_IDENT_FICHA_PSICOSOCIAL_SITUACION_RIESGO_SOCIAL";
    public static final String SECCION_FICHA_IDENT_EVALUACION_SOCIAL_DOMICILIARIA = "SECCION_FICHA_IDENT_EVALUACION_SOCIAL_DOMICILIARIA";
    public static final String SECCION_FICHA_IDENT_EVALUACION_SOCIAL_ORIENTACION_CONSEJERIA_FAMILIAR = "SECCION_FICHA_IDENT_EVALUACION_SOCIAL_ORIENTACION_CONSEJERIA_FAMILIAR";
    public static final String SECCION_FICHA_IDENT_EVALUACION_SOCIAL_SEGUIMIENTO_SOCIAL = "SECCION_FICHA_IDENT_EVALUACION_SOCIAL_SEGUIMIENTO_SOCIAL";
    public static final String SECCION_FICHA_IDENT_EVALUACION_SOCIAL_AUTORIZACION_VISITANTES = "SECCION_FICHA_IDENT_EVALUACION_SOCIAL_AUTORIZACION_VISITANTES";
    public static final String SECCION_FICHA_IDENT_HISTORIA_CLINICA = "SECCION_FICHA_IDENT_HISTORIA_CLINICA";
    public static final String SECCION_FICHA_IDENT_EVALUACION_SALUD = "SECCION_FICHA_IDENT_EVALUACION_SALUD";
    public static final String SECCION_FICHA_IDENT_EVALUACIONES_PSICOLOGICAS = "SECCION_FICHA_IDENT_EVALUACIONES_PSICOLOGICAS";
    public static final String SECCION_FICHA_IDENT_NIVEL_RIESGO = "SECCION_FICHA_IDENT_NIVEL_RIESGO";
    public static final String SECCION_FICHA_IDENT_EVALUACION_CONDUCTUAL = "SECCION_FICHA_IDENT_EVALUACION_CONDUCTUAL";
    public static final String SECCION_FICHA_IDENT_PLAN_TRATAMIENTO = "SECCION_FICHA_IDENT_PLAN_TRATAMIENTO";
    public static final String SECCION_FICHA_IDENT_INFORMES = "SECCION_FICHA_IDENT_INFORMES";
    public static final String SECCION_FICHA_IDENT_PERMISO_SALIDA = "SECCION_FICHA_IDENT_PERMISO_SALIDA";
    public static final String SECCION_FICHA_IDENT_SANCIONES_DISCIPLINARIAS = "SECCION_FICHA_IDENT_SANCIONES_DISCIPLINARIAS";
    public static final String SECCION_FICHA_IDENT_PROGRAMA_INTERVENCION_INTENSIVA = "SECCION_FICHA_IDENT_PROGRAMA_INTERVENCION_INTENSIVA";
    public static final String SECCION_FICHA_IDENT_NOTIFICACIONES = "SECCION_FICHA_IDENT_NOTIFICACIONES";
    public static final String SECCION_FICHA_IDENT_PREPARACION_EGRESO = "SECCION_FICHA_IDENT_PREPARACION_EGRESO";
    public static final String SECCION_FICHA_IDENT_INFORME_FINAL = "SECCION_FICHA_IDENT_INFORME_FINAL";
    public static final String SECCION_FICHA_IDENT_POST_EGRESO = "SECCION_FICHA_IDENT_POST_EGRESO";
    public static final String SECCION_FICHA_IDENT_FLUJOS = "SECCION_FICHA_IDENT_FLUJOS";

    //Tipos de foto en el historial
    public static final String NEMONICO_TIPO_HISTORIAL_ARCHIVOS = "NEMONICO_TIPO_HISTORIAL_ARCHIVOS";
    public static final String NEMONICO_TIPO_HISTORIAL_ARCHIVOS_REGISTRO_CIVIL = "NEMONICO_TIPO_HISTORIAL_ARCHIVOS_REGISTRO_CIVIL";
    public static final String NEMONICO_TIPO_HISTORIAL_ARCHIVOS_OTROS = "NEMONICO_TIPO_HISTORIAL_ARCHIVOS_OTROS";
    public static final String NEMONICO_TIPO_HISTORIAL_ARCHIVOS_FRONTAL = "NEMONICO_TIPO_HISTORIAL_ARCHIVOS_FRONTAL";
    public static final String NEMONICO_TIPO_HISTORIAL_ARCHIVOS_PERFIL_IZQUIERDO = "NEMONICO_TIPO_HISTORIAL_ARCHIVOS_PERFIL_IZQUIERDO";
    public static final String NEMONICO_TIPO_HISTORIAL_ARCHIVOS_PERFIL_DERECHO = "NEMONICO_TIPO_HISTORIAL_ARCHIVOS_PERFIL_DERECHO";
    public static final String NEMONICO_TIPO_HISTORIAL_ARCHIVOS_GOLPE = "NEMONICO_TIPO_HISTORIAL_ARCHIVOS_GOLPE";
    public static final String NEMONICO_TIPO_HISTORIAL_ARCHIVOS_MARCA_DE_CUERPO = "NEMONICO_TIPO_HISTORIAL_ARCHIVOS_MARCA_DE_CUERPO";

    //Acciones en el historial de fotos
    public static final String ACCION_HISTORIAL_FOTOS = "ACCION_HISTORIAL_FOTOS";
    public static final String ACCION_HISTORIAL_FOTOS_SUBIR = "ACCION_HISTORIAL_FOTOS_SUBIR";
    public static final String ACCION_HISTORIAL_FOTOS_OBTENER = "ACCION_HISTORIAL_FOTOS_OBTENER";
    public static final String ACCION_HISTORIAL_FOTOS_ELIMINAR = "ACCION_HISTORIAL_FOTOS_ELIMINAR";
    public static final String ACCION_HISTORIAL_FOTOS_EDITAR = "ACCION_HISTORIAL_FOTOS_EDITAR";

    //Gestion evento de fugas
    public static final String ACCION_LISTAR_EVENTOS_FUGA = "LISTAR_EVENTOS_FUGA";
    public static final String ACCION_CREAR_EVENTO_FUGA = "CREAR_EVENTO_FUGA";
    public static final String ACCION_OBTENER_EVENTO_FUGA = "OBTENER_EVENTO_FUGA";
    public static final String ACCION_ACTUALIZAR_EVENTO_FUGA = "ACTUALIZAR_EVENTO_FUGA";
    public static final String ACCION_ELIMINAR_EVENTO_FUGA = "ELIMINAR_EVENTO_FUGA";


    //Nemonico acciones Restablecimiento de contraseñas
    public static final String ACCION_USUARIO_REESTABLECIMIENTO_CONTRASENIA = "ACCION_USUARIO_REESTABLECIMIENTO_CONTRASENIA";
    public static final String ACCION_USUARIO_REESTABLECIMIENTO_CONTRASENIA_VERIFICACION_EMAIL = "ACCION_USUARIO_REESTABLECIMIENTO_CONTRASENIA_VERIFICACION_EMAIL";
    public static final String ACCION_USUARIO_REESTABLECIMIENTO_CONTRASENIA_INGRESO_NUEVA_CONTRASENIA = "ACCION_USUARIO_REESTABLECIMIENTO_CONTRASENIA_INGRESO_NUEVA_CONTRASENIA";

    //Evaluacion Salud
    public static final String ACCION_OBTENER_ENFERMEDADES_PERSONA_RELACIONADA = "ACCION_OBTENER_ENFERMEDADES_PERSONA_RELACIONADA";
    public static final String ACCION_OBTENER_ENFERMEDADES_RELACIONADAS = "ACCION_OBTENER_ENFERMEDADES_RELACIONADAS";

    //Registro de salida
    public static final String ACCION_LISTAR_REGISTRO_SALIDA = "LISTAR_REGISTRO_SALIDA";
    public static final String ACCION_CREAR_REGISTRO_SALIDA = "CREAR_REGISTRO_SALIDA";
    public static final String ACCION_OBTENER_REGISTRO_SALIDA = "OBTENER_REGISTRO_SALIDA";
    public static final String ACCION_ACTUALIZAR_REGISTRO_SALIDA = "ACTUALIZAR_REGISTRO_SALIDA";
    public static final String ACCION_ELIMINAR_REGISTRO_SALIDA = "ELIMINAR_REGISTRO_SALIDA";

    // Acciones para Seguimientos Psicológicos
    public static final String ACCION_OBTENER_SEGUIMIENTOS_PSICOLOGICOS = "OBTENER_SEGUIMIENTOS_PSICOLOGICOS";
    public static final String ACCION_CREAR_SEGUIMIENTO_PSICOLOGICO = "CREAR_SEGUIMIENTO_PSICOLOGICO";
    public static final String ACCION_EDITAR_SEGUIMIENTO_PSICOLOGICO = "EDITAR_SEGUIMIENTO_PSICOLOGICO";
    public static final String ACCION_ACTUALIZAR_SEGUIMIENTO_PSICOLOGICO = "ACTUALIZAR_SEGUIMIENTO_PSICOLOGICO";
    public static final String ACCION_ELIMINAR_SEGUIMIENTO_PSICOLOGICO = "ELIMINAR_SEGUIMIENTO_PSICOLOGICO";

    // Acciones para Seguimientos Conductuales
    public static final String ACCION_OBTENER_SEGUIMIENTOS_CONDUCTUALES = "OBTENER_SEGUIMIENTOS_CONDUCTUALES";
    public static final String ACCION_CREAR_SEGUIMIENTO_CONDUCTUAL = "CREAR_SEGUIMIENTO_CONDUCTUAL";
    public static final String ACCION_EDITAR_SEGUIMIENTO_CONDUCTUAL = "EDITAR_SEGUIMIENTO_CONDUCTUAL";
    public static final String ACCION_ACTUALIZAR_SEGUIMIENTO_CONDUCTUAL = "ACTUALIZAR_SEGUIMIENTO_CONDUCTUAL";
    public static final String ACCION_ELIMINAR_SEGUIMIENTO_CONDUCTUAL = "ELIMINAR_SEGUIMIENTO_CONDUCTUAL";

    // Acciones para Seguimiento Social
    public static final String ACCION_OBTENER_SEGUIMIENTO_SOCIAL = "ACCION_OBTENER_SEGUIMIENTO_SOCIAL";
    public static final String ACCION_CREAR_SEGUIMIENTO_SOCIAL = "ACCION_CREAR_SEGUIMIENTO_SOCIAL";
    public static final String ACCION_EDITAR_SEGUIMIENTO_SOCIAL = "ACCION_EDITAR_SEGUIMIENTO_SOCIAL";
    public static final String ACCION_ELIMINAR_SEGUIMIENTO_SOCIAL = "ACCION_ELIMINAR_SEGUIMIENTO_SOCIAL";
    
    // Acciones para Cargos
    public static final String ACCION_OBTENER_CARGOS_JERARQUIA_VALIDOS = "ACCION_OBTENER_CARGOS_JERARQUIA";
    public static final String ACCION_ELIMINAR_CARGOS_JERARQUIA = "ACCION_ELIMINAR_CARGOS_JERARQUIA";
    public static final String ACCION_EDITAR_CARGOS_JERARQUIA = "ACCION_EDITAR_CARGOS_JERARQUIA";
    public static final String ACCION_CREAR_CARGOS_JERARQUIA = "ACCION_CREAR_CARGOS_JERARQUIA";
    
    // Acciones para Localidad
    public static final String ACCION_OBTENER_LOCALIDAD = "ACCION_OBTENER_LOCALIDAD";
    public static final String ACCION_CREAR_LOCALIDAD = "ACCION_CREAR_LOCALIDAD";
    public static final String ACCION_EDITAR_LOCALIDAD = "ACCION_EDITAR_LOCALIDAD";

    //Acta de Externamiento
    public static final String ACCION_OBTENER_ACTAS_EXTERNAMIENTO = "OBTENER_ACTAS_EXTERNAMIENTO";
    public static final String ACCION_CREAR_ACTA_EXTERNAMIENTO = "CREAR_ACTA_EXTERNAMIENTO";
    public static final String ACCION_ACTUALIZAR_ACTA_EXTERNAMIENTO = "ACTUALIZAR_ACTA_EXTERNAMIENTO";
    public static final String ACCION_ELIMINAR_ACTA_EXTERNAMIENTO = "ELIMINAR_ACTA_EXTERNAMIENTO";
    public static final String ACCION_SUBIR_ACTA_EXTERNAMIENTO = "SUBIR_ACTA_EXTERNAMIENTO";

    //ACTIVIDADES INTERVENCION DIFERENCIADA
    public static final String ACCION_EDITAR_ACTIVIDAD_INTERVENCION = "ACCION_EDITAR_ACTIVIDAD_INTERVENCION";
    public static final String ACCION_CREAR_ACTIVIDAD_INTERVENCION = "ACCION_CREAR_ACTIVIDAD_INTERVENCION";

    //ACTIVIDADES INTERVENCION DIFERENCIADA SEGUIMIENTO
    public static final String ACCION_EDITAR_ACTIVIDAD_SEGUIMIENTO = "ACCION_EDITAR_ACTIVIDAD_SEGUIMIENTO";
    public static final String ACCION_CREAR_ACTIVIDAD_SEGUIMIENTO = "ACCION_CREAR_ACTIVIDAD_SEGUIMIENTO";
    //Registro de instituciones
    public static final String ACCION_LISTAR_REGISTRO_INSTITUCION = "LISTAR_REGISTRO_INSTITUCION";
    public static final String ACCION_CREAR_REGISTRO_INSTITUCION = "CREAR_REGISTRO_INSTITUCION";
    public static final String ACCION_OBTENER_REGISTRO_INSTITUCION = "OBTENER_REGISTRO_INSTITUCION";
    public static final String ACCION_ACTUALIZAR_REGISTRO_INSTITUCION = "ACTUALIZAR_REGISTRO_INSTITUCION";
    public static final String ACCION_ELIMINAR_REGISTRO_INSTITUCION = "ELIMINAR_REGISTRO_INSTITUCION";

    //Registro de seguimientos instituciones
    public static final String ACCION_LISTAR_SEGUIMIENTO_INSTITUCION = "LISTAR_SEGUIMIENTO_INSTITUCION";
    public static final String ACCION_CREAR_SEGUIMIENTO_INSTITUCION = "CREAR_SEGUIMIENTO_INSTITUCION";
    public static final String ACCION_OBTENER_SEGUIMIENTO_INSTITUCION = "OBTENER_SEGUIMIENTO_INSTITUCION";
    public static final String ACCION_ACTUALIZAR_SEGUIMIENTO_INSTITUCION = "ACTUALIZAR_SEGUIMIENTO_INSTITUCION";
    public static final String ACCION_ELIMINAR_SEGUIMIENTO_INSTITUCION = "ELIMINAR_SEGUIMIENTO_INSTITUCION";

    //Permiso de salida
    public static final String ACCION_CREAR_PERMISO_SALIDA = "CREAR_PERMISO_SALIDA";
    public static final String ACCION_ACTUALIZAR_PERMISO_SALIDA = "ACTUALIZAR_PERMISO_SALIDA";
    public static final String ACCION_ELIMINAR_PERMISO_SALIDA = "ELIMINAR_PERMISO_SALIDA";
    public static final String ACCION_OBTENER_PERMISO_SALIDA = "ELIMINAR_OBTENER_PERMISO_SALIDA";


    //AdolescenteDerivado
    public static final String ACCION_CREAR_ADOLESCENTE_DERIVADO = "CREAR_ADOLESCENTE_DERIVADO";
    public static final String ACCION_ACTUALIZAR_ADOLESCENTE_DERIVADO = "ACTUALIZAR_ADOLESCENTE_DERIVADO";
    public static final String ACCION_ELIMINAR_ADOLESCENTE_DERIVADO = "ELIMINAR_ADOLESCENTE_DERIVADO";
    public static final String ACCION_OBTENER_ADOLESCENTE_DERIVADO = "OBTENER_ADOLESCENTE_DERIVADO";

    //Seguimiento adolescente
    public static final String ACCION_CREAR_SEGUIMIENTO_ADOLESCENTE = "CREAR_SEGUIMIENTO_ADOLESCENTE";
    public static final String ACCION_ACTUALIZAR_SEGUIMIENTO_ADOLESCENTE = "ACTUALIZAR_SEGUIMIENTO_ADOLESCENTE";
    public static final String ACCION_ELIMINAR_SEGUIMIENTO_ADOLESCENTE = "ELIMINAR_SEGUIMIENTO_ADOLESCENTE";
    public static final String ACCION_BUSCAR_SEGUIMIENTO_ADOLESCENTE = "BUSCAR_SEGUIMIENTO_ADOLESCENTE";

    //Contacto adolescente
    public static final String ACCION_CREAR_CONTACTO_ADOLESCENTE = "CREAR_CONTACTO_ADOLESCENTE";
    public static final String ACCION_ACTUALIZAR_CONTACTO_ADOLESCENTE = "ACTUALIZAR_CONTACTO_ADOLESCENTE";
    public static final String ACCION_ELIMINAR_CONTACTO_ADOLESCENTE = "ELIMINAR_CONTACTO_ADOLESCENTE";
    public static final String ACCION_BUSCAR_CONTACTO_ADOLESCENTE = "BUSCAR_CONTACTO_ADOLESCENTE";

    //FICHA MEDICA
    public static final String ACCION_CREAR_FICHA_MEDICA = "ACCION_CREAR_FICHA_MEDICA";
    public static final String ACCION_ACTUALIZAR_FICHA_MEDICA = "ACCION_ACTUALIZAR_FICHA_MEDICA";
    public static final String ACCION_OBTENER_FICHA_MEDICA = "ACCION_OBTENER_FICHA_MEDICA";

    // Acciones CRUD para reforzamiento
    public static final String ACCION_CREAR_REFORZAMIENTO = "ACCION_CREAR_REFORZAMIENTO";
    public static final String ACCION_EDITAR_REFORZAMIENTO = "ACCION_EDITAR_REFORZAMIENTO";
    public static final String ACCION_REMOVER_REFORZAMIENTO = "ACCION_REMOVER_REFORZAMIENTO";
    public static final String ACCION_OBTENER_REFORZAMIENTOS = "ACCION_OBTENER_REFORZAMIENTOS";
    public static final String ACCION_OBTENER_REFORZAMIENTO_DOCUMENTO = "ACCION_OBTENER_REFORZAMIENTO_DOCUMENTO";

    // Acciones de auditoría para Alertas
    public static final String ACCION_OBTENER_ALERTA = "ACCION_OBTENER_ALERTA";
    public static final String ACCION_CREAR_ALERTA = "ACCION_CREAR_ALERTA";
    public static final String ACCION_EDITAR_ALERTA = "ACCION_EDITAR_ALERTA";
    public static final String ACCION_ELIMINAR_ALERTA = "ACCION_ELIMINAR_ALERTA";

    //ESTADOS PTI
    public static final String NEMONICO_ESTADO_PTI_ACTIVO= "ESTADO_PTI_ACTIVO";
    public static final String NEMONICO_ESTADO_PTI_BORRADOR= "ESTADO_PTI_BORRADOR";
    public static final String NEMONICO_ESTADO_PTI_FINALIZADO= "ESTADO_PTI_FINALIZADO";
    
    // Acciones para catálogos
    public static final String ACCION_OBTENER_CATALOGOS = "ACCION_OBTENER_CATALOGOS";
    public static final String ACCION_CREAR_CATALOGO = "ACCION_CREAR_CATALOGO";
    public static final String ACCION_EDITAR_CATALOGO = "ACCION_EDITAR_CATALOGO";
    public static final String ACCION_ELIMINAR_CATALOGO = "ACCION_ELIMINAR_CATALOGO";
    public static final String ACCION_BUSCAR_CATALOGOS = "ACCION_BUSCAR_CATALOGOS";

    // Acciones para Ubicación Jerarquía
    public static final String ACCION_OBTENER_UBICACION_JERARQUIA = "ACCION_OBTENER_UBICACION_JERARQUIA";
    public static final String ACCION_CREAR_UBICACION_JERARQUIA = "ACCION_CREAR_UBICACION_JERARQUIA";
    public static final String ACCION_EDITAR_UBICACION_JERARQUIA = "ACCION_EDITAR_UBICACION_JERARQUIA";
    public static final String ACCION_ELIMINAR_UBICACION_JERARQUIA = "ACCION_ELIMINAR_UBICACION_JERARQUIA";
    public static final String ACCION_OBTENER_FICHA_UBICACION = "ACCION_OBTENER_FICHA_UBICACION";
    public static final String ACCION_CREAR_FICHA_UBICACION = "ACCION_CREAR_FICHA_UBICACION";
    public static final String ACCION_EDITAR_FICHA_UBICACION = "ACCION_EDITAR_FICHA_UBICACION";
    public static final String ACCION_ELIMINAR_FICHA_UBICACION = "ACCION_ELIMINAR_FICHA_UBICACION";

    // Acciones para clasificación de enfermedades
    public static final String ACCION_OBTENER_CLASIFICACION_ENFERMEDADES = "ACCION_OBTENER_CLASIFICACION_ENFERMEDADES";

    // Acciones para Medicamentos
    public static final String ACCION_OBTENER_MEDICAMENTOS = "ACCION_OBTENER_MEDICAMENTOS";

    // Acciones para Especialidad Producto
    public static final String ACCION_OBTENER_ESPECIALIDAD_PRODUCTOS = "ACCION_OBTENER_ESPECIALIDAD_PRODUCTOS";

    //ESTADOS BANDEJA BORRADORES
    public static final String ACCION_OBTENER_LISTA_BANDEJAS_BORRADORES= "ACCION_OBTENER_LISTA_BANDEJAS_BORRADORES";
    public static final String ACCION_CREAR_BANDEJAS_BORRADORES = "ACCION_CREAR_BANDEJAS_BORRADORES";
    public static final String ACCION_EDITAR_BANDEJAS_BORRADORES = "ACCION_EDITAR_BANDEJAS_BORRADORES";
    public static final String ACCION_ELIMINAR_BANDEJAS_BORRADORES = "ACCION_ELIMINAR_BANDEJAS_BORRADORES";


    //ESTADOS SANCIONES DISCIPLINARIAS
    public static final String ACCION_OBTENER_LISTA_SANCION_DISCIPLINARIA= "ACCION_OBTENER_LISTA_SANCION_DISCIPLINARIA";
    public static final String ACCION_CREAR_SANCION_DISCIPLINARIA = "ACCION_CREAR_SANCION_DISCIPLINARIA";
    public static final String ACCION_ACTUALIZAR_SANCION_DISCIPLINARIA = "ACCION_ACTUALIZAR_SANCION_DISCIPLINARIA";
    public static final String ACCION_ELIMINAR_SANCION_DISCIPLINARIA = "ACCION_ELIMINAR_SANCION_DISCIPLINARIA";

    //Permisos por rol usuario
    public static final String ACCION_CREAR_PERMISO_MENU_ROL_USUARIO = "CREAR_PERMISO_MENU_ROL_USUARIO";
    public static final String ACCION_ACTUALIZAR_PERMISO_MENU_ROL_USUARIO = "ACTUALIZAR_PERMISO_MENU_ROL_USUARIO";
    public static final String ACCION_ELIMINAR_PERMISO_MENU_ROL_USUARIO = "ELIMINAR_PERMISO_MENU_ROL_USUARIO";
    public static final String ACCION_OBTENER_PERMISO_MENU_ROL_USUARIO = "OBTENER_PERMISO_MENU_ROL_USUARIO";
    public static final String ACCION_LISTAR_PERMISOS_MENU_ROL_USUARIO = "LISTAR_PERMISOS_MENU_ROL_USUARIO";

    //Acciones permisos ficha identificación
    public static final String ACCIONES_MENU_PERMISO_ROL_USUARIO = "ACCIONES_MENU_PERMISO_ROL_USUARIO";
    public static final String ACCIONES_MENU_PERMISO_AGREGAR = "ACCIONES_MENU_PERMISO_ROL_USUARIO_AGREGAR";
    public static final String ACCIONES_MENU_PERMISO_VER = "ACCIONES_MENU_PERMISO_ROL_USUARIO_VER";
    public static final String ACCIONES_MENU_PERMISO_EDITAR = "ACCIONES_MENU_PERMISO_ROL_USUARIO_EDITAR";
    public static final String ACCIONES_MENU_PERMISO_ELIMINAR = "ACCIONES_MENU_PERMISO_ROL_USUARIO_ELIMINAR";

    //Nemonicos permisos usuario rol
    public static final String NEMONICO_PERMISO_TIPO_PERMISO_ESTANDAR = "PERMISO_TIPO_PERMISO_ESTANDAR";
    public static final String NEMONICO_PERMISO_TIPO_EXCLUSION_JORNADA = "PERMISO_TIPO_EXCLUSION_JORNADA";

    //Acciones reportesa
    public static final String ACCION_LISTAR_REPORTE_ADOLESCENTES_EXTERNADOS = "LISTAR_REPORTE_ADOLESCENTES_EXTERNADOS";
    public static final String ACCION_EXPORTAR_ADOLESCENTES = "ACCION_EXPORTAR_ADOLESCENTES";

    // Nemonicos de estados de adolescente
    public static final String NEMONICO_ESTADO_ADOLESCENTE_LIBRE = "ESTADO_ADOLESCENTE_LIBRE";
    public static final String NEMONICO_ESTADO_ADOLESCENTE_FUGADO = "ESTADO_ADOLESCENTE_FUGADO";


    //Acciones trabajo laboral
    public static final String ACCION_CREAR_TRABAJO_LABORAL = "ACCION_CREAR_TRABAJO_LABORAL";
    public static final String ACCION_ELIMINAR_TRABAJO_LABORAL = "ACCION_ELIMINAR_TRABAJO_LABORAL";
    public static final String ACCION_LISTAR_TRABAJO_LABORAL = "ACCION_LISTAR_TRABAJO_LABORAL";


    //Acciones estudios
    public static final String ACCION_CREAR_ESTUDIOS = "ACCION_CREAR_ESTUDIOS";
    public static final String ACCION_ELIMINAR_ESTUDIOS = "ACCION_ELIMINAR_ESTUDIOS";
    // Acciones dashboard
    public static final String ACCION_LISTAR_DASHBOARD_CENTROS = "ACCION_LISTAR_DASHBOARD_CENTROS";
    public static final String ACCION_LISTAR_DASHBOARD_ESTADISTICAS = "ACCION_LISTAR_DASHBOARD_ESTADISTICAS";

    // Tipo de entrada de ingreso
    public static final String TIPO_ENTRADA_TRASLADO = "ENTRADA_TRASLADO";
    public static final String TIPO_ENTRADA_INGRESO_NUEVO = "ENTRADA_INGRESO_NUEVO";
    public static final String TIPO_ENTRADA_SALIDA_TEMPORAL = "ENTRADA_SALIDA_TEMPORAL";
    public static final String TIPO_ENTRADA_FUGA = "ENTRADA_FUGA";

}

