-- Align SAVRY encuesta 59 (SIGAI) with siserv indicadores
-- Generated automatically. Target: dbpronacejqa2 via 42.14
BEGIN;

-- 1) Soft-remove 'Otros' questions (inactive in siserv)
UPDATE enc_pregunta SET removido=true, requerido=false, fecha_edicion=now() WHERE id_pregunta=915 AND removido IS DISTINCT FROM true;
UPDATE enc_pregunta SET removido=true, requerido=false, fecha_edicion=now() WHERE id_pregunta=922 AND removido IS DISTINCT FROM true;
UPDATE enc_pregunta SET removido=true, requerido=false, fecha_edicion=now() WHERE id_pregunta=931 AND removido IS DISTINCT FROM true;
UPDATE enc_pregunta SET removido=true, requerido=false, fecha_edicion=now() WHERE id_pregunta=938 AND removido IS DISTINCT FROM true;

-- 2) Align question titles (typos / wording)
UPDATE enc_pregunta SET texto='Delincuencia en grupo de iguales (Descripción y motivación)', fecha_edicion=now() WHERE id_pregunta=916 AND texto ILIKE '%Delicuencia%';
UPDATE enc_pregunta SET texto='Asunción de riesgos/impulsividad (Descripción y motivación)', fecha_edicion=now() WHERE id_pregunta=924;

-- 3) Replace option labels with siserv clinical indicadores (prefixed Bajo/Medio/Alto or Presente/Ausente)
UPDATE enc_respuesta SET respuesta='Bajo — El adolescente no ha tenido situaciones de comportamiento violento, donde ha causado daño a otra persona', fecha_edicion=now() WHERE id_pregunta=905 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El adolescente tuvo algunas situaciones de comportamiento violento, donde ha causado daño a otra persona.', fecha_edicion=now() WHERE id_pregunta=905 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El adolescente tuvo diversas situaciones de comportamiento violento, donde ha causado daño a otra persona.', fecha_edicion=now() WHERE id_pregunta=905 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El adolescente no ha participado en actividades delictivas que no conlleven una agresión tales como robar y/o vender de droga', fecha_edicion=now() WHERE id_pregunta=906 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El adolescente ha participado en menos de cinco ocasiones en actividades delictivas que no conlleven una agresión tales como robar y/o vender de droga', fecha_edicion=now() WHERE id_pregunta=906 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El adolescente ha participado en cinco o más ocasiones en actividades delictivas que no conlleven una agresión tales como robar y/o vender de droga', fecha_edicion=now() WHERE id_pregunta=906 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El adolescente no ha tenido comportamiento violento grave que cause daño físico a otra persona, o el primer acto violento se realizó cuando tenía 14 años o más', fecha_edicion=now() WHERE id_pregunta=907 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Entre los 11 y 13 años de edad, el adolescente ha tenido algun  comportamiento violento  que causó daño físico a otra persona, pero nada de gravedad', fecha_edicion=now() WHERE id_pregunta=907 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Antes de los 11 años, el adolescente ha tenido comportamiento violento grave que causó daño físico a otra persona', fecha_edicion=now() WHERE id_pregunta=907 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El adolescente no ha tenido ninguna intervencion, de salud mental ni judicial*.', fecha_edicion=now() WHERE id_pregunta=908 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El adolescente estuvo recibiendo en una o dos oportunidades  intervenciones especializadas en salud mental o cumpliendo una medida judicial  dejandolo inconcluso*.', fecha_edicion=now() WHERE id_pregunta=908 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — En tres o más ocasiones, el adolescente incumplio la intervencion especializada en salud mental o judicial*.', fecha_edicion=now() WHERE id_pregunta=908 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El adolescente niega intentos de autolesión o haber atentado contra su vida.', fecha_edicion=now() WHERE id_pregunta=909 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El adolescente refiere eventos de autolesión "leve" sin requerir algún tipo de atención médica y sin intención clara de suicidio.', fecha_edicion=now() WHERE id_pregunta=909 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El adolescente tiene intentos a autolesión grave por lo que requirió atención médica y/o hospitalización; con presencia de intento suicida evidente.', fecha_edicion=now() WHERE id_pregunta=909 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — No ha presenciado actos violentos entre los miembros de su hogar.', fecha_edicion=now() WHERE id_pregunta=910 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Ha presenciado en algunas ocasiones agresiones físicas (bofetadas, empujones) entre los miembros de su hogar.', fecha_edicion=now() WHERE id_pregunta=910 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Ha presenciado diversas agresiones físicas (bofetadas, empujones) entre los miembros de su hogar; y/o situación de violencia grave donde uno de los miembros requirió atención médica producto del acto violento.', fecha_edicion=now() WHERE id_pregunta=910 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — Durante la niñez no ha sufrido maltrato físico o trato negligente.', fecha_edicion=now() WHERE id_pregunta=911 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Durante la niñez, en pocas ocasiones, sufrió maltrato físico y trato negligente (carente de supervisión y sin los principales cuidados).', fecha_edicion=now() WHERE id_pregunta=911 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Durante la niñez, frecuentemente, sufrió maltrato físico y trato negligente (carente de supervisión y sin los principales cuidados).', fecha_edicion=now() WHERE id_pregunta=911 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — Ninguno de los padres o cuidadores del adolescente tienen antecedentes de conductas delictivas en la edad adulta.', fecha_edicion=now() WHERE id_pregunta=912 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Uno o más de los padres/cuidadores del adolescente han cometido menos de cinco actos delictivos poco graves en la edad adulta.', fecha_edicion=now() WHERE id_pregunta=912 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Uno o más de los padres/cuidadores del adolescente han cometido cinco a más actos delictivos graves en la edad adulta.', fecha_edicion=now() WHERE id_pregunta=912 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — En la etapa de la niñez, el adolescente recibió los principales cuidados de forma constante por parte de uno o más de los padres/cuidadores.', fecha_edicion=now() WHERE id_pregunta=913 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — En la etapa de niñez, el adolescente pasó un periado breve alejado de sus padres o cuidadores principales, es decir, se encontró en albergues, centros de rehabilitación, y/o en casa de otros parientes.*', fecha_edicion=now() WHERE id_pregunta=913 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — En la etapa de la niñez, el adolescente permaneció más de un año alejado de sus padres o cuidadores principales, encontrándose en albergues, centros de rehabilitación, y/o en casa de otros parientes.*', fecha_edicion=now() WHERE id_pregunta=913 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El adolescente, durante su etapa escolar, ha tenido un adecuado rendimiento académico (notas promedio y resultados positivos en clase). No refiere antecedentes de haber suspendido algún curso.', fecha_edicion=now() WHERE id_pregunta=914 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El adolescente, durante su etapa escolar, ha presentado algunas dificultades académicas; obteniendo notas por debajo del promedio, pero no ha tenido antecedentes de abandono escolar*.', fecha_edicion=now() WHERE id_pregunta=914 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El adolescente, durante su etapa escolar, ha presentado frecuentemente notas por debajo del promedio, con antecedente de abandono escolar.', fecha_edicion=now() WHERE id_pregunta=914 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El adolescente que no se afilia a pares con conductas delictivas.', fecha_edicion=now() WHERE id_pregunta=916 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El adolescente se afilia de manera ocasional con pares que delinquen, pero si se relaciona regularmente con pares de conductas antisociales poco frecuentes o de poca gravedad.', fecha_edicion=now() WHERE id_pregunta=916 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El adolescente suele afiliarse de manera frecuente con otros jóvenes que delinquen y que regularmente realizan conductas antisociales, relacionadas a, robos, bandas delictivas, uso de armas, violencia.', fecha_edicion=now() WHERE id_pregunta=916 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — No ha experimentado rechazo en el pasado y ni en la actualidad.', fecha_edicion=now() WHERE id_pregunta=917 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Tiene antecedentes de haber sufrido cierto rechazo por su grupo de pares, pero nada grave, ni habitual; recientemente no atraviesa por ningún tipo de rechazo.', fecha_edicion=now() WHERE id_pregunta=917 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Ha sufrido rechazo significativo durante la mayor parte de su infancia y adolescencia por su grupo de iguales.', fecha_edicion=now() WHERE id_pregunta=917 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — Muestra capacidad apropiada para su edad para hacer frente a las dificultades de estrés que se le presente.', fecha_edicion=now() WHERE id_pregunta=918 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Generalmente muestra una capacidad adecuada para hacer frente a situaciones de estrés o dificultades.', fecha_edicion=now() WHERE id_pregunta=918 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — No presenta la capacidad adecuada para hacer frente a situaciones de estrés o dificultades que se le presenten.', fecha_edicion=now() WHERE id_pregunta=918 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El adolescente está siendo educado por los padres en una disciplina consistente; recibe una supervisión apropiada y hay implicancia de los padres en las actividades del menor.', fecha_edicion=now() WHERE id_pregunta=919 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El adolescente ha tenido una disciplina a veces inconsistente, ya que no es tan estricta, ni tan permisiva y en los últimos meses la supervisión a sido poco fiable.', fecha_edicion=now() WHERE id_pregunta=919 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El adolescente está siendo educado en una disciplina inconsistente, con un estilo de crianza mayormente permisivo, con autoridad debilitada, con falta de supervisión, limites e insuficiente implicancia de los padres en las actividades del menor.', fecha_edicion=now() WHERE id_pregunta=919 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — Cuenta con algún familiar o tutor que son capaces y están dispuestos de ofrecerle soporte emocional y otros.', fecha_edicion=now() WHERE id_pregunta=920 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Cuenta con soporte de algún familiar o tutor, sin embargo, no es de forma permanente y en ocasiones no es fiable.', fecha_edicion=now() WHERE id_pregunta=920 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — No cuenta con ningún sustento que tenga la disponibilidad y/o deseo de ofrecer soporte emocional y una tutoría de apoyo.', fecha_edicion=now() WHERE id_pregunta=920 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — Vive en un entorno que no presenta índices de marginalidad, con bajos niveles de delincuencia.', fecha_edicion=now() WHERE id_pregunta=921 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Vive en un entorno con algunos problemas relacionados a la delincuencia, venta de drogas, entre otros.', fecha_edicion=now() WHERE id_pregunta=921 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El entorno donde se ha desarrollado el adolescente presenta características de marginalidad debido a los altos índices de delincuencia y violencia.', fecha_edicion=now() WHERE id_pregunta=921 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — No muestra actitudes relacionadas a la violencia. Así mismo tiene la capacidad de generar soluciones no agresivas a los problemas y no tiende a malinterpretar intenciones hostiles o agresivas en otros.', fecha_edicion=now() WHERE id_pregunta=923 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Muestra algunas actitudes que apoyen la legitimidad de la delincuencia o de la violencia. Así mismo muestra algunas dificultades para generar soluciones no agresivas a los problemas, ligera tendencia a malinterpretar las intenciones hostiles o agresivas de los demás.', fecha_edicion=now() WHERE id_pregunta=923 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Aprueba claramente actitudes y valores que aprueban la delincuencia o el uso de la violencia. Muestra grandes dificultades para generar soluciones no agresivas a los problemas y tiene con frecuencia a malinterpretar las intenciones hostiles o agresivas de los otros.', fecha_edicion=now() WHERE id_pregunta=923 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — No tiene problemas de para evaluar situaciones de riesgos o de control de sus impulsos.', fecha_edicion=now() WHERE id_pregunta=924 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El/ La Joven tiene algunos pequeños o poco importantes comportamientos de asunción de riesgos o de impulsividad.', fecha_edicion=now() WHERE id_pregunta=924 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El/ La Joven tiene comportamientos importantes de asunción de riesgos o de impulsividad.', fecha_edicion=now() WHERE id_pregunta=924 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — No tiene dificultades relacionados con el consumo de alcohol y drogas.', fecha_edicion=now() WHERE id_pregunta=925 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — No ha abusado recientemente de alcohol o drogas, pero tiene una historia de problemas de abuso de las mismas*.', fecha_edicion=now() WHERE id_pregunta=925 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Está experimentando en este momento dificultades graves relacionadas con el consumo de SPA.', fecha_edicion=now() WHERE id_pregunta=925 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — Presenta una habilidad adecuada a su edad para expresar y manejar los sentimientos del enfado.', fecha_edicion=now() WHERE id_pregunta=926 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Presenta una dificultad moderada para controlar expresiones de enfado.', fecha_edicion=now() WHERE id_pregunta=926 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Presenta una dificultad importante para controlar expresiones de enfado en las que se puede mencionar como amenaza a otros, hacerles daño o en las cuales daña gravemente objetos.', fecha_edicion=now() WHERE id_pregunta=926 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — Adecuada capacidad de remordimiento y empatía  a su edad.', fecha_edicion=now() WHERE id_pregunta=927 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Presenta una dificultad moderada en el sentimiento de remordimiento. Muestra poca emoción de angustia como respuesta de arrepentimiento por su propia mala conducta, (exceptuando el reconocimiento verbal) y/o dificultad moderada para expresar empatía (en ocasiones minimiza las consecuencias).', fecha_edicion=now() WHERE id_pregunta=927 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Presenta una dificultad importante de experimentar remordimiento (no muestra emoción de angustia como respuesta de arrepentimiento por su propia mala conducta, no admite haberse equivocado); dificultad importante en la capacidad para expresar empatía (se puede mostrar es indiferente a los sentimientos de los demás; es insensible a los efectos negativos de su comportamiento en los demás).', fecha_edicion=now() WHERE id_pregunta=927 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — Durante la entrevista, no se han observado dificultades de inquietud, hiperactividad o problemas de concentración.', fecha_edicion=now() WHERE id_pregunta=928 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — Durante la entrevista, se ha observado dificultades moderadas de inquietud, hiperactividad o problemas de concentración.', fecha_edicion=now() WHERE id_pregunta=928 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — Durante la entrevista, se ha observado dificultades graves de inquietud, hiperactividad o problemas de concentración.', fecha_edicion=now() WHERE id_pregunta=928 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El joven entiende la necesidad de una intervención profesional y muestra una actitud positiva hacia  la supervisión durante su permanencia en el centro juvenil.', fecha_edicion=now() WHERE id_pregunta=929 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El joven se encuentra en proceso de tener una actitud positiva frente a la intervención psicoeducativas. La adherencia al programa de tratamiento se encuentra en su etapa inicial.', fecha_edicion=now() WHERE id_pregunta=929 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El joven no cree que él esté en riesgo por lo que no aprecia la necesidad de la intervención psicoeducativa. El Joven demuestra una motivación baja para el éxito o cumplimiento de la intervención manifestando a menudo actitudes negativas hacia las intervenciones o hacia los proveedores del tratamiento.', fecha_edicion=now() WHERE id_pregunta=929 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Bajo — El joven muestra interés y compromiso escolar y/o laboral*.', fecha_edicion=now() WHERE id_pregunta=930 AND removido IS NOT TRUE AND (respuesta = 'Bajo' OR respuesta LIKE 'Bajo — %' OR respuesta LIKE 'Bajo — %');
UPDATE enc_respuesta SET respuesta='Medio — El joven presenta poco interés y compromiso escolar y/o laboral, sin embargo, quisiera retomar los estudios y/o comprometerse en lo laboral*.', fecha_edicion=now() WHERE id_pregunta=930 AND removido IS NOT TRUE AND (respuesta = 'Moderado' OR respuesta LIKE 'Moderado — %' OR respuesta LIKE 'Medio — %');
UPDATE enc_respuesta SET respuesta='Alto — El joven presenta un bajo interés o compromiso escolar y/o laboral registrando reiteradas llamadas de atención por su inasistencia*.', fecha_edicion=now() WHERE id_pregunta=930 AND removido IS NOT TRUE AND (respuesta = 'Alto' OR respuesta LIKE 'Alto — %' OR respuesta LIKE 'Alto — %');
UPDATE enc_respuesta SET respuesta='Presente — Participa en actividades socialmente aceptables como: deportivas, académicas, artísticas o se afilia a pares que participan en ese tipo de actividades.', fecha_edicion=now() WHERE id_pregunta=932 AND removido IS NOT TRUE AND (respuesta = 'Presencia' OR respuesta LIKE 'Presencia — %' OR respuesta LIKE 'Presente — %');
UPDATE enc_respuesta SET respuesta='Ausente — Participa un poco o nada en actividades socialmente aceptables o en grupo de iguales prosociales', fecha_edicion=now() WHERE id_pregunta=932 AND removido IS NOT TRUE AND (respuesta = 'Ausencia' OR respuesta LIKE 'Ausencia — %' OR respuesta LIKE 'Ausente — %');
UPDATE enc_respuesta SET respuesta='Presente — Cuenta con apoyo de personas que le brindan soporte emocional y lo desaconsejan del uso de violencia y delincuencia.*recibe consejeria de psicologos en su club.', fecha_edicion=now() WHERE id_pregunta=933 AND removido IS NOT TRUE AND (respuesta = 'Presencia' OR respuesta LIKE 'Presencia — %' OR respuesta LIKE 'Presente — %');
UPDATE enc_respuesta SET respuesta='Ausente — No cuenta con apoyo de personas que le brindan soporte emocional y lo desaconsejen del uso de violencia y delincuencia.', fecha_edicion=now() WHERE id_pregunta=933 AND removido IS NOT TRUE AND (respuesta = 'Ausencia' OR respuesta LIKE 'Ausencia — %' OR respuesta LIKE 'Ausente — %');
UPDATE enc_respuesta SET respuesta='Presente — El adolescente cuenta con fuertes vínculos afectivos con al menos un adulto prosocial que lo motiva a salir adelante.', fecha_edicion=now() WHERE id_pregunta=934 AND removido IS NOT TRUE AND (respuesta = 'Presencia' OR respuesta LIKE 'Presencia — %' OR respuesta LIKE 'Presente — %');
UPDATE enc_respuesta SET respuesta='Ausente — El adolescente no cuenta con fuertes vínculos afectivos con al menos un adulto prosocial que lo motiva a salir adelante.', fecha_edicion=now() WHERE id_pregunta=934 AND removido IS NOT TRUE AND (respuesta = 'Ausencia' OR respuesta LIKE 'Ausencia — %' OR respuesta LIKE 'Ausente — %');
UPDATE enc_respuesta SET respuesta='Presente — El adolescente presenta una actitud favorable, se muestra asequible y reconoce la importancia de la intervención del profesional o autoridad.', fecha_edicion=now() WHERE id_pregunta=935 AND removido IS NOT TRUE AND (respuesta = 'Presencia' OR respuesta LIKE 'Presencia — %' OR respuesta LIKE 'Presente — %');
UPDATE enc_respuesta SET respuesta='Ausente — El adolescente no muestra una actitud favorable hacia la intervención, se muestra reacio, no colabora con la intervención profesional.', fecha_edicion=now() WHERE id_pregunta=935 AND removido IS NOT TRUE AND (respuesta = 'Ausencia' OR respuesta LIKE 'Ausencia — %' OR respuesta LIKE 'Ausente — %');
UPDATE enc_respuesta SET respuesta='Presente — Muestra un alto nivel de interés, implicación y motivación por tener buenos resultados ya sea en la escuela o en el trabajo.', fecha_edicion=now() WHERE id_pregunta=936 AND removido IS NOT TRUE AND (respuesta = 'Presencia' OR respuesta LIKE 'Presencia — %' OR respuesta LIKE 'Presente — %');
UPDATE enc_respuesta SET respuesta='Ausente — No muestra un alto nivel de interés, implicación y motivación por tener buenos resultados, ya sea en la escuela o en el trabajo.', fecha_edicion=now() WHERE id_pregunta=936 AND removido IS NOT TRUE AND (respuesta = 'Ausencia' OR respuesta LIKE 'Ausencia — %' OR respuesta LIKE 'Ausente — %');
UPDATE enc_respuesta SET respuesta='Presente — Se aprecia que el adolescente tiene habilidades asociadas al razonamiento, solución de conflictos o facilidad de adaptación a cambios.', fecha_edicion=now() WHERE id_pregunta=937 AND removido IS NOT TRUE AND (respuesta = 'Presencia' OR respuesta LIKE 'Presencia — %' OR respuesta LIKE 'Presente — %');
UPDATE enc_respuesta SET respuesta='Ausente — Se aprecia que el adolescente no tiene habilidades asociadas al razonamiento, solución de conflictos o facilidad de adaptación a cambios.', fecha_edicion=now() WHERE id_pregunta=937 AND removido IS NOT TRUE AND (respuesta = 'Ausencia' OR respuesta LIKE 'Ausencia — %' OR respuesta LIKE 'Ausente — %');

-- 4) Verification
SELECT s.orden, left(s.nombre,40) seccion, count(p.*) FILTER (WHERE p.removido IS NOT TRUE) activas, count(p.*) FILTER (WHERE p.removido IS TRUE) removidas FROM enc_seccion s LEFT JOIN enc_pregunta p ON p.id_seccion=s.id_seccion WHERE s.id_encuesta=59 GROUP BY s.orden, s.nombre ORDER BY 1;
SELECT p.id_pregunta, left(p.texto,50) preg, r.orden, left(r.respuesta,80) resp FROM enc_pregunta p JOIN enc_respuesta r ON r.id_pregunta=p.id_pregunta WHERE p.id_pregunta IN (905,924,932) AND r.removido IS NOT TRUE ORDER BY 1,3;
COMMIT;
